import type { Job, MarketingPartner, JobFairEvent } from "@/types";

export const JOBS: Job[] = [
  {
    id: "job-001",
    title: "Caregiver Lansia (Kaigo)",
    company: "Sakura Care Group",
    offTaker: "APJATI",
    country: "Jepang",
    countryFlag: "🇯🇵",
    sector: "Care Worker",
    salaryMin: 15000000,
    salaryMax: 22000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-01T00:00:00Z",
    deadline: "2025-04-30T00:00:00Z",
    positions: 20,
    description:
      "Kami mencari Caregiver profesional untuk merawat lansia di fasilitas perawatan premium di Tokyo. Anda akan bekerja dalam tim multikultural, mendapat pelatihan bahasa Jepang, dan tinggal di asrama bersubsidi. Posisi ini sangat cocok untuk perawat berpengalaman yang ingin berkarir di Jepang dengan dukungan penuh dari APJATI.",
    qualifications: [
      "Minimal pendidikan D3 Keperawatan atau Kebidanan",
      "Bersedia mengikuti pelatihan bahasa Jepang intensif selama 3 bulan",
      "Usia 22–35 tahun",
      "Sehat jasmani dan rohani",
      "Memiliki sertifikat JLPT N4 atau bersedia mengikuti pelatihan",
      "Pengalaman merawat lansia minimal 1 tahun (diutamakan)",
    ],
    benefits: [
      "Tiket pesawat pulang pergi ditanggung perusahaan",
      "Akomodasi asrama gratis di dekat tempat kerja",
      "Asuransi kesehatan dan jiwa lengkap",
      "Uang makan ¥30,000/bulan",
      "Cuti tahunan 14 hari + libur nasional Jepang",
    ],
    isFunded: true,
    funderName: "Kementerian Ketenagakerjaan RI",
    fundingCoverage: "Biaya training penuh (Rp 8.500.000)",
    mpChannel: "zenius",
    skillRequirements: [
      { skillName: "Basic Thinking Skills", requiredLevel: 70, userLevel: 45 },
      {
        skillName: "Understanding and Be Effective with Others",
        requiredLevel: 80,
        userLevel: 60,
      },
      {
        skillName: "Communication in Japanese/Korean/English",
        requiredLevel: 65,
        userLevel: 20,
      },
      {
        skillName: "Productivity and Management Skills",
        requiredLevel: 55,
        userLevel: 55,
      },
    ],
    isJobFair: true,
    jobFairEventId: "jf-2025-q1",
  },
  {
    id: "job-002",
    title: "Operator Produksi (Monozukuri)",
    company: "Toyota Manufacturing Indonesia → Japan",
    offTaker: "Vokati",
    country: "Jepang",
    countryFlag: "🇯🇵",
    sector: "Manufacturing",
    salaryMin: 18000000,
    salaryMax: 25000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-05T00:00:00Z",
    deadline: "2025-05-15T00:00:00Z",
    positions: 35,
    description:
      "Program Magang Spesifikasi Keterampilan (SSW) di lini produksi otomotif Jepang. Anda akan bekerja di pabrik modern dengan teknologi terkini, mendapat pelatihan langsung dari insinyur Jepang, dan berpeluang mendapat kontrak perpanjangan 3 tahun. Program ini dijalankan resmi melalui Vokati.",
    qualifications: [
      "Lulusan SMK Teknik Mesin, Elektro, atau Otomotif",
      "Usia 18–30 tahun",
      "Fisik sehat dan tidak buta warna",
      "Bersedia ditempatkan di Aichi, Osaka, atau Kanagawa",
      "Tidak bertato",
      "Lulus tes kemampuan dasar bahasa Jepang (JLPT N5)",
    ],
    benefits: [
      "Tiket pesawat PP ditanggung",
      "Asrama pabrik bersubsidi ¥20,000/bulan",
      "Makan siang di kantin pabrik",
      "Asuransi kesehatan dan kecelakaan kerja",
      "Bonus lembur sesuai regulasi Jepang",
    ],
    isFunded: false,
    mpChannel: "telkomsel",
    skillRequirements: [
      { skillName: "Basic Thinking Skills", requiredLevel: 60, userLevel: 45 },
      {
        skillName: "Basic Decision-Making",
        requiredLevel: 55,
        userLevel: 30,
      },
      {
        skillName: "Productivity and Management Skills",
        requiredLevel: 65,
        userLevel: 55,
      },
      {
        skillName: "Communication in Japanese/Korean/English",
        requiredLevel: 50,
        userLevel: 20,
      },
    ],
    isJobFair: true,
    jobFairEventId: "jf-2025-q1",
  },
  {
    id: "job-003",
    title: "Pekerja Manufaktur (EPS-TOPIK)",
    company: "Samsung SDI Korea",
    offTaker: "Vokati",
    country: "Korea Selatan",
    countryFlag: "🇰🇷",
    sector: "Manufacturing",
    salaryMin: 17000000,
    salaryMax: 23000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-08T00:00:00Z",
    deadline: "2025-04-20T00:00:00Z",
    positions: 50,
    description:
      "Rekrutmen resmi melalui sistem EPS-TOPIK untuk bekerja di fasilitas manufaktur baterai Samsung di Gyeonggi-do. Pekerja akan mendapatkan kontrak 4 tahun 10 bulan yang dapat diperpanjang, dengan upah minimum Korea yang kompetitif. Program ini dikelola langsung oleh Vokati dan Pemerintah Korea.",
    qualifications: [
      "Lulus ujian bahasa Korea (EPS-TOPIK) atau bersedia mengikuti persiapan",
      "Usia 18–38 tahun",
      "Tidak pernah memiliki riwayat overstay di Korea",
      "Sehat fisik dan mental",
      "Lulusan minimal SMA/SMK",
    ],
    benefits: [
      "Gaji mengikuti upah minimum Korea (KRW 2.060.740/bulan)",
      "Asuransi 4 jenis (kesehatan, pensiun, kecelakaan, pengangguran)",
      "Tiket pesawat PP oleh pemerintah",
      "Tunjangan akomodasi",
    ],
    isFunded: true,
    funderName: "Pemerintah Korea & Vokati",
    fundingCoverage: "Biaya ujian & tiket (senilai Rp 6.200.000)",
    mpChannel: "zenius",
    skillRequirements: [
      { skillName: "Basic Thinking Skills", requiredLevel: 55, userLevel: 45 },
      {
        skillName: "Communication in Japanese/Korean/English",
        requiredLevel: 70,
        userLevel: 20,
      },
      {
        skillName: "Basic Decision-Making",
        requiredLevel: 50,
        userLevel: 30,
      },
    ],
    isJobFair: false,
  },
  {
    id: "job-004",
    title: "Asisten Rumah Tangga (PLRT)",
    company: "Hong Kong Domestic Agency",
    offTaker: "APJATI",
    country: "Hong Kong",
    countryFlag: "🇭🇰",
    sector: "Care Worker",
    salaryMin: 8500000,
    salaryMax: 10000000,
    salaryCurrency: "IDR",
    postedAt: "2025-02-20T00:00:00Z",
    deadline: "2025-04-15T00:00:00Z",
    positions: 100,
    description:
      "Peluang bekerja sebagai Pekerja Rumah Tangga (PRT) di Hong Kong dengan gaji minimum resmi HK$4,870/bulan. Anda akan tinggal bersama majikan, mendapat hari libur Minggu penuh, dan perlindungan hukum yang kuat dari pemerintah HK. APJATI memastikan proses legal dan transparan.",
    qualifications: [
      "Perempuan, usia 21–45 tahun",
      "Minimal lulusan SMP (diutamakan SMA)",
      "Bisa berbahasa Inggris dasar (berkomunikasi sehari-hari)",
      "Pengalaman bekerja sebagai PRT minimal 1 tahun",
      "Sehat fisik dan tidak memiliki penyakit menular",
    ],
    benefits: [
      "Gaji minimum HK$4,870/bulan (~Rp 9.700.000)",
      "Tempat tinggal dan makan oleh majikan",
      "Tiket pesawat PP ditanggung majikan",
      "Asuransi kesehatan dari majikan",
      "Libur penuh setiap hari Minggu",
    ],
    isFunded: false,
    mpChannel: "zenius",
    skillRequirements: [
      {
        skillName: "Understanding and Be Effective with Others",
        requiredLevel: 75,
        userLevel: 60,
      },
      {
        skillName: "Communication in Japanese/Korean/English",
        requiredLevel: 60,
        userLevel: 20,
      },
      {
        skillName: "Basic Thinking Skills",
        requiredLevel: 50,
        userLevel: 45,
      },
    ],
    isJobFair: false,
  },
  {
    id: "job-005",
    title: "Barista & F&B Crew",
    company: "Jumeirah Beach Hotel",
    offTaker: "APJATI",
    country: "UAE",
    countryFlag: "🇦🇪",
    sector: "Hospitality",
    salaryMin: 12000000,
    salaryMax: 18000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-10T00:00:00Z",
    deadline: "2025-05-01T00:00:00Z",
    positions: 15,
    description:
      "Bergabung dengan tim F&B di salah satu hotel bintang lima terkemuka di Dubai. Posisi ini meliputi persiapan minuman, layanan tamu premium, dan operasional kafe. Anda akan bekerja di lingkungan internasional dengan standar hospitality kelas dunia dan berpeluang mendapat promosi ke posisi senior.",
    qualifications: [
      "Pengalaman barista atau F&B minimal 1 tahun",
      "Kemampuan bahasa Inggris minimal intermediate (bisa berkomunikasi dengan tamu)",
      "Penampilan rapi dan ramah",
      "Bersedia bekerja shift termasuk malam dan weekend",
      "Usia 20–32 tahun",
    ],
    benefits: [
      "Gaji AED 1,800–2,800/bulan + tip",
      "Akomodasi staff gratis",
      "Makan 3x sehari di kantin hotel",
      "Tiket pesawat PP setahun sekali",
      "Asuransi medis internasional",
      "Peluang promosi karir",
    ],
    isFunded: true,
    funderName: "Program CSR BNI",
    fundingCoverage: "Subsidi sertifikasi hospitality (Rp 4.500.000)",
    mpChannel: "telkomsel",
    skillRequirements: [
      {
        skillName: "Understanding and Be Effective with Others",
        requiredLevel: 80,
        userLevel: 60,
      },
      {
        skillName: "Communication in Japanese/Korean/English",
        requiredLevel: 75,
        userLevel: 20,
      },
      {
        skillName: "Productivity and Management Skills",
        requiredLevel: 60,
        userLevel: 55,
      },
      {
        skillName: "Business and Economics for Everyone",
        requiredLevel: 45,
        userLevel: 35,
      },
    ],
    isJobFair: true,
    jobFairEventId: "jf-2025-q1",
  },
  {
    id: "job-006",
    title: "Formwork Carpenter",
    company: "Al Habtoor Group",
    offTaker: "Vokati",
    country: "UAE",
    countryFlag: "🇦🇪",
    sector: "Construction",
    salaryMin: 10000000,
    salaryMax: 15000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-12T00:00:00Z",
    deadline: "2025-04-28T00:00:00Z",
    positions: 40,
    description:
      "Dibutuhkan Formwork Carpenter berpengalaman untuk proyek konstruksi skala besar di Abu Dhabi dan Dubai. Anda akan bekerja pada proyek-proyek infrastruktur dan hunian mewah dengan manajemen konstruksi internasional. Kontrak 2 tahun dengan opsi perpanjangan.",
    qualifications: [
      "Pengalaman formwork minimal 2 tahun",
      "Memiliki sertifikat K3 konstruksi (diutamakan)",
      "Kemampuan membaca gambar teknik dasar",
      "Fisik kuat, bersedia bekerja outdoor",
      "Usia 22–40 tahun",
    ],
    benefits: [
      "Gaji AED 1,400–2,200/bulan",
      "Camp worker bersubsidi",
      "Makan gratis di mess",
      "Asuransi kecelakaan kerja",
      "Tiket pesawat PP per tahun",
      "Lembur dibayar 125% dari gaji normal",
    ],
    isFunded: false,
    mpChannel: "zenius",
    skillRequirements: [
      { skillName: "Basic Thinking Skills", requiredLevel: 55, userLevel: 45 },
      {
        skillName: "Basic Decision-Making",
        requiredLevel: 60,
        userLevel: 30,
      },
      {
        skillName: "Productivity and Management Skills",
        requiredLevel: 65,
        userLevel: 55,
      },
    ],
    isJobFair: true,
    jobFairEventId: "jf-2025-q1",
  },
  {
    id: "job-007",
    title: "Hotel Room Attendant",
    company: "Marina Bay Sands",
    offTaker: "APJATI",
    country: "Singapura",
    countryFlag: "🇸🇬",
    sector: "Hospitality",
    salaryMin: 11000000,
    salaryMax: 15000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-02T00:00:00Z",
    deadline: "2025-04-20T00:00:00Z",
    positions: 12,
    description:
      "Kesempatan bekerja sebagai Room Attendant di Marina Bay Sands — ikon hospitality Singapura. Anda akan bertanggung jawab menjaga kebersihan dan kerapian kamar tamu kelas dunia, dengan standar operasional tertinggi. Singapura menawarkan lingkungan kerja aman, gaji kompetitif, dan kesempatan berkembang.",
    qualifications: [
      "Minimal lulusan SMA/SMK",
      "Pengalaman housekeeping hotel bintang 3+ (diutamakan)",
      "Kemampuan bahasa Inggris percakapan",
      "Rapi, teliti, dan berorientasi detail",
      "Usia 21–35 tahun",
    ],
    benefits: [
      "Gaji SGD 1,600–2,100/bulan",
      "Akomodasi staff di dekat properti",
      "Makan 1x/shift",
      "Asuransi medis",
      "Tiket pesawat PP setahun sekali",
      "MRT pass bersubsidi",
    ],
    isFunded: false,
    skillRequirements: [
      {
        skillName: "Understanding and Be Effective with Others",
        requiredLevel: 70,
        userLevel: 60,
      },
      {
        skillName: "Communication in Japanese/Korean/English",
        requiredLevel: 60,
        userLevel: 20,
      },
      {
        skillName: "Productivity and Management Skills",
        requiredLevel: 60,
        userLevel: 55,
      },
    ],
    isJobFair: false,
  },
  {
    id: "job-008",
    title: "Caregiver Anak (Childminder)",
    company: "Nippon Kids Care",
    offTaker: "APJATI",
    country: "Jepang",
    countryFlag: "🇯🇵",
    sector: "Care Worker",
    salaryMin: 13000000,
    salaryMax: 18000000,
    salaryCurrency: "IDR",
    postedAt: "2025-02-25T00:00:00Z",
    deadline: "2025-04-10T00:00:00Z",
    positions: 8,
    description:
      "Posisi Childminder untuk merawat anak usia 0–6 tahun di pusat penitipan anak di Osaka. Anda akan bekerja bersama tim Jepang yang hangat, mendapat pelatihan child development dari Jepang, dan tinggal di kota yang aman dan nyaman. Sangat cocok untuk calon perawat anak yang ingin pengalaman internasional.",
    qualifications: [
      "Pendidikan D3/S1 PAUD, Keperawatan, atau Psikologi",
      "Sabar, kreatif, dan menyukai anak-anak",
      "Kemampuan bahasa Jepang dasar (N5) atau bersedia belajar",
      "Usia 22–32 tahun",
    ],
    benefits: [
      "Gaji ¥160,000–220,000/bulan",
      "Asrama bersubsidi",
      "Asuransi kesehatan Jepang",
      "Tiket pesawat PP",
      "Pelatihan bahasa Jepang lanjutan gratis",
    ],
    isFunded: true,
    funderName: "Dinas Ketenagakerjaan Jawa Timur",
    fundingCoverage: "Pelatihan bahasa & sertifikasi (Rp 7.200.000)",
    mpChannel: "zenius",
    skillRequirements: [
      {
        skillName: "Understanding and Be Effective with Others",
        requiredLevel: 85,
        userLevel: 60,
      },
      { skillName: "Basic Thinking Skills", requiredLevel: 65, userLevel: 45 },
      {
        skillName: "Communication in Japanese/Korean/English",
        requiredLevel: 60,
        userLevel: 20,
      },
      {
        skillName: "Basic Decision-Making",
        requiredLevel: 55,
        userLevel: 30,
      },
    ],
    isJobFair: false,
  },
  {
    id: "job-009",
    title: "Welding Specialist (Teknik Las)",
    company: "Hyundai Heavy Industries",
    offTaker: "Vokati",
    country: "Korea Selatan",
    countryFlag: "🇰🇷",
    sector: "Manufacturing",
    salaryMin: 20000000,
    salaryMax: 28000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-15T00:00:00Z",
    deadline: "2025-05-20T00:00:00Z",
    positions: 25,
    description:
      "Rekrutmen Juru Las untuk industri galangan kapal Hyundai di Ulsan, Korea. Posisi ini membutuhkan keahlian MIG/TIG welding dengan sertifikasi internasional. Upah sangat kompetitif dengan banyak peluang lembur. Program ini melalui jalur SSW (Specified Skilled Worker) resmi Vokati.",
    qualifications: [
      "Sertifikat las SMAW/MIG/TIG level 2 ke atas",
      "Pengalaman las industri minimal 2 tahun",
      "Lulus tes bahasa Korea tingkat dasar",
      "Fisik kuat, tidak takut ketinggian",
      "Usia 20–39 tahun",
    ],
    benefits: [
      "Gaji KRW 2.500.000–3.500.000/bulan + lembur",
      "Asuransi 4 jenis wajib",
      "Dorm pekerja",
      "Makan di kantin",
      "Tiket PP oleh Vokati",
    ],
    isFunded: false,
    mpChannel: "telkomsel",
    skillRequirements: [
      {
        skillName: "Basic Decision-Making",
        requiredLevel: 65,
        userLevel: 30,
      },
      {
        skillName: "Productivity and Management Skills",
        requiredLevel: 70,
        userLevel: 55,
      },
      { skillName: "Basic Thinking Skills", requiredLevel: 60, userLevel: 45 },
    ],
    isJobFair: false,
  },
  {
    id: "job-010",
    title: "Front Desk Agent",
    company: "Mandarin Oriental Singapore",
    offTaker: "APJATI",
    country: "Singapura",
    countryFlag: "🇸🇬",
    sector: "Hospitality",
    salaryMin: 13000000,
    salaryMax: 17000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-07T00:00:00Z",
    deadline: "2025-04-25T00:00:00Z",
    positions: 6,
    description:
      "Bergabunglah sebagai Front Desk Agent di Mandarin Oriental Singapore, hotel bintang lima dengan reputasi kelas dunia. Anda akan menjadi wajah hotel, mengelola check-in/check-out tamu, dan memberikan layanan concierge terbaik. Peluang karir ke posisi Guest Relations Manager dalam 2–3 tahun.",
    qualifications: [
      "D3/S1 Hospitality, Pariwisata, atau Komunikasi",
      "Bahasa Inggris fasih (wajib), Mandarin nilai plus",
      "Penampilan profesional, ramah, dan percaya diri",
      "Pengalaman di front office hotel bintang 4+ (diutamakan)",
      "Usia 21–30 tahun",
    ],
    benefits: [
      "Gaji SGD 1,800–2,400/bulan",
      "Akomodasi bersubsidi",
      "Training program berstandar international",
      "Meal allowance per shift",
      "Medical & dental coverage",
    ],
    isFunded: true,
    funderName: "Program Scholarship Kemnaker",
    fundingCoverage: "Sertifikasi bahasa & hospitality (Rp 5.500.000)",
    mpChannel: "zenius",
    skillRequirements: [
      {
        skillName: "Communication in Japanese/Korean/English",
        requiredLevel: 85,
        userLevel: 20,
      },
      {
        skillName: "Understanding and Be Effective with Others",
        requiredLevel: 85,
        userLevel: 60,
      },
      {
        skillName: "Business and Economics for Everyone",
        requiredLevel: 50,
        userLevel: 35,
      },
      {
        skillName: "Productivity and Management Skills",
        requiredLevel: 65,
        userLevel: 55,
      },
    ],
    isJobFair: false,
  },
  {
    id: "job-011",
    title: "Heavy Equipment Operator",
    company: "BESIX Group Middle East",
    offTaker: "Vokati",
    country: "UAE",
    countryFlag: "🇦🇪",
    sector: "Construction",
    salaryMin: 14000000,
    salaryMax: 20000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-11T00:00:00Z",
    deadline: "2025-05-05T00:00:00Z",
    positions: 30,
    description:
      "Dibutuhkan operator alat berat (excavator, bulldozer, crane) untuk proyek infrastruktur mega di UAE. Anda akan bergabung dalam tim konstruksi internasional di bawah manajemen BESIX, salah satu kontraktor terbesar di dunia. Kontrak 2 tahun yang bisa diperpanjang.",
    qualifications: [
      "SIM alat berat yang masih berlaku",
      "Pengalaman minimal 3 tahun sebagai operator alat berat",
      "Sertifikat K3 alat berat (diutamakan)",
      "Fisik prima, bersedia bekerja di cuaca panas",
      "Usia 25–42 tahun",
    ],
    benefits: [
      "Gaji AED 2,000–3,200/bulan",
      "Overtime rate AED 20–30/jam",
      "Camp dengan AC",
      "Makan 3x gratis",
      "Asuransi kecelakaan kerja",
      "Tiket PP setiap tahun",
    ],
    isFunded: false,
    skillRequirements: [
      {
        skillName: "Basic Decision-Making",
        requiredLevel: 70,
        userLevel: 30,
      },
      {
        skillName: "Productivity and Management Skills",
        requiredLevel: 70,
        userLevel: 55,
      },
      { skillName: "Basic Thinking Skills", requiredLevel: 65, userLevel: 45 },
    ],
    isJobFair: false,
  },
  {
    id: "job-012",
    title: "Food Processing Worker",
    company: "Kagome Co., Ltd.",
    offTaker: "Vokati",
    country: "Jepang",
    countryFlag: "🇯🇵",
    sector: "Manufacturing",
    salaryMin: 14000000,
    salaryMax: 19000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-14T00:00:00Z",
    deadline: "2025-05-10T00:00:00Z",
    positions: 18,
    description:
      "Bergabung dengan Kagome — perusahaan food & beverage terkemuka Jepang — sebagai Food Processing Worker di fasilitas produksi modern di Shizuoka. Anda akan bekerja dalam lini produksi saus tomat dan minuman kesehatan dengan standar kebersihan tingkat tinggi. Cocok untuk fresh graduate.",
    qualifications: [
      "Lulusan SMK/D3 semua jurusan",
      "Usia 18–28 tahun",
      "Tidak alergi terhadap produk makanan",
      "Bersedia bekerja shift (pagi/sore)",
      "Kemampuan bahasa Jepang N5 atau mengikuti pelatihan",
    ],
    benefits: [
      "Gaji ¥170,000–230,000/bulan",
      "Asrama pabrik bersubsidi",
      "Makan siang gratis di kantin",
      "Asuransi kesehatan Jepang",
      "Bonus tahunan",
    ],
    isFunded: true,
    funderName: "Program G2G Indonesia-Jepang",
    fundingCoverage: "Pelatihan bahasa & medical check-up (Rp 9.000.000)",
    mpChannel: "zenius",
    skillRequirements: [
      { skillName: "Basic Thinking Skills", requiredLevel: 55, userLevel: 45 },
      {
        skillName: "Productivity and Management Skills",
        requiredLevel: 60,
        userLevel: 55,
      },
      {
        skillName: "Communication in Japanese/Korean/English",
        requiredLevel: 45,
        userLevel: 20,
      },
      {
        skillName: "Basic Decision-Making",
        requiredLevel: 50,
        userLevel: 30,
      },
    ],
    isJobFair: false,
  },
  {
    id: "job-013",
    title: "Software Developer",
    company: "Tech Solutions Singapore",
    offTaker: "APJATI",
    country: "Singapura",
    countryFlag: "🇸🇬",
    sector: "IT",
    salaryMin: 18000000,
    salaryMax: 28000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-13T00:00:00Z",
    deadline: "2025-05-15T00:00:00Z",
    positions: 10,
    description:
      "Bergabung dengan tim pengembangan software di Singapura. Anda akan mengerjakan proyek fintech dan e-commerce dengan stack modern. Lingkungan kerja internasional dengan peluang karir ke posisi senior.",
    qualifications: [
      "S1 Teknik Informatika atau sejenis",
      "Pengalaman 2+ tahun dengan React/Node.js",
      "Bahasa Inggris aktif",
      "Portfolio atau GitHub",
    ],
    benefits: [
      "Gaji SGD 3,500–5,500/bulan",
      "Remote work 2 hari/minggu",
      "Asuransi kesehatan",
      "Training budget tahunan",
    ],
    isFunded: false,
    mpChannel: "zenius",
    skillRequirements: [
      { skillName: "Basic Thinking Skills", requiredLevel: 75, userLevel: 45 },
      {
        skillName: "Communication in Japanese/Korean/English",
        requiredLevel: 80,
        userLevel: 20,
      },
      {
        skillName: "Productivity and Management Skills",
        requiredLevel: 70,
        userLevel: 55,
      },
    ],
    isJobFair: false,
  },
  {
    id: "job-014",
    title: "Nurse Assistant (Kangoshi)",
    company: "Tokyo Medical Center",
    offTaker: "APJATI",
    country: "Jepang",
    countryFlag: "🇯🇵",
    sector: "Care Worker",
    salaryMin: 16000000,
    salaryMax: 21000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-09T00:00:00Z",
    deadline: "2025-04-30T00:00:00Z",
    positions: 15,
    description:
      "Asisten perawat di rumah sakit Tokyo. Bekerja di unit rawat inap dengan tim perawat Jepang. Pelatihan bahasa dan sertifikasi disediakan.",
    qualifications: [
      "D3/S1 Keperawatan",
      "JLPT N4 atau bersedia pelatihan",
      "Usia 22–35 tahun",
    ],
    benefits: [
      "Gaji ¥180,000–250,000/bulan",
      "Asrama bersubsidi",
      "Asuransi kesehatan",
    ],
    isFunded: true,
    funderName: "Kemenkes RI",
    fundingCoverage: "Pelatihan bahasa (Rp 6.000.000)",
    mpChannel: "telkomsel",
    skillRequirements: [
      {
        skillName: "Understanding and Be Effective with Others",
        requiredLevel: 80,
        userLevel: 60,
      },
      {
        skillName: "Communication in Japanese/Korean/English",
        requiredLevel: 70,
        userLevel: 20,
      },
    ],
    isJobFair: true,
    jobFairEventId: "jf-2025-q1",
  },
  {
    id: "job-015",
    title: "Electrician",
    company: "Dubai Construction Co",
    offTaker: "Vokati",
    country: "UAE",
    countryFlag: "🇦🇪",
    sector: "Construction",
    salaryMin: 12000000,
    salaryMax: 17000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-11T00:00:00Z",
    deadline: "2025-05-08T00:00:00Z",
    positions: 22,
    description:
      "Teknisi listrik untuk proyek gedung dan infrastruktur di Dubai. Instalasi dan maintenance sistem elektrikal.",
    qualifications: [
      "Sertifikat ahli listrik",
      "Pengalaman 3+ tahun",
      "Bisa baca gambar teknis",
    ],
    benefits: [
      "Gaji AED 1,800–2,500/bulan",
      "Camp worker",
      "Tiket PP tahunan",
    ],
    isFunded: false,
    mpChannel: "zenius",
    skillRequirements: [
      {
        skillName: "Basic Decision-Making",
        requiredLevel: 65,
        userLevel: 30,
      },
      {
        skillName: "Productivity and Management Skills",
        requiredLevel: 70,
        userLevel: 55,
      },
    ],
    isJobFair: false,
  },
  {
    id: "job-016",
    title: "Kitchen Helper",
    company: "Grand Hyatt Hong Kong",
    offTaker: "APJATI",
    country: "Hong Kong",
    countryFlag: "🇭🇰",
    sector: "Hospitality",
    salaryMin: 9000000,
    salaryMax: 12000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-06T00:00:00Z",
    deadline: "2025-04-22T00:00:00Z",
    positions: 8,
    description:
      "Helper dapur di hotel bintang lima Hong Kong. Persiapan bahan, kebersihan dapur, dan dukungan chef.",
    qualifications: [
      "Pengalaman dapur minimal 1 tahun",
      "Sehat fisik",
      "Bisa bahasa Inggris dasar",
    ],
    benefits: [
      "Gaji HK$5,200–6,500/bulan",
      "Akomodasi staff",
      "Makan shift",
    ],
    isFunded: false,
    skillRequirements: [
      {
        skillName: "Productivity and Management Skills",
        requiredLevel: 60,
        userLevel: 55,
      },
      {
        skillName: "Understanding and Be Effective with Others",
        requiredLevel: 55,
        userLevel: 60,
      },
    ],
    isJobFair: false,
  },
  {
    id: "job-017",
    title: "Quality Control Inspector",
    company: "LG Electronics Korea",
    offTaker: "Vokati",
    country: "Korea Selatan",
    countryFlag: "🇰🇷",
    sector: "Manufacturing",
    salaryMin: 15000000,
    salaryMax: 20000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-14T00:00:00Z",
    deadline: "2025-05-12T00:00:00Z",
    positions: 14,
    description:
      "QC Inspector di pabrik elektronik LG. Pemeriksaan kualitas produk, dokumentasi, dan koordinasi dengan tim produksi.",
    qualifications: [
      "SMK/D3 Teknik",
      "Detail-oriented",
      "Bisa bahasa Korea dasar",
    ],
    benefits: [
      "Gaji KRW 2.200.000–2.800.000/bulan",
      "Dorm",
      "Asuransi 4 jenis",
    ],
    isFunded: true,
    funderName: "Program G2G",
    fundingCoverage: "Pelatihan (Rp 4.000.000)",
    mpChannel: "zenius",
    skillRequirements: [
      { skillName: "Basic Thinking Skills", requiredLevel: 65, userLevel: 45 },
      {
        skillName: "Productivity and Management Skills",
        requiredLevel: 70,
        userLevel: 55,
      },
    ],
    isJobFair: false,
  },
  {
    id: "job-018",
    title: "Housekeeping Supervisor",
    company: "Raffles Hotel Singapore",
    offTaker: "APJATI",
    country: "Singapura",
    countryFlag: "🇸🇬",
    sector: "Hospitality",
    salaryMin: 14000000,
    salaryMax: 19000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-10T00:00:00Z",
    deadline: "2025-05-01T00:00:00Z",
    positions: 5,
    description:
      "Supervisor housekeeping di hotel mewah. Mengawasi tim room attendant dan memastikan standar kebersihan.",
    qualifications: [
      "Pengalaman housekeeping 3+ tahun",
      "Leadership skills",
      "Bahasa Inggris lancar",
    ],
    benefits: [
      "Gaji SGD 2,200–3,000/bulan",
      "Akomodasi",
      "Medical coverage",
    ],
    isFunded: false,
    mpChannel: "telkomsel",
    skillRequirements: [
      {
        skillName: "Understanding and Be Effective with Others",
        requiredLevel: 80,
        userLevel: 60,
      },
      {
        skillName: "Productivity and Management Skills",
        requiredLevel: 75,
        userLevel: 55,
      },
    ],
    isJobFair: false,
  },
  {
    id: "job-019",
    title: "Assembly Line Worker",
    company: "Panasonic Japan",
    offTaker: "Vokati",
    country: "Jepang",
    countryFlag: "🇯🇵",
    sector: "Manufacturing",
    salaryMin: 15000000,
    salaryMax: 20000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-12T00:00:00Z",
    deadline: "2025-05-18T00:00:00Z",
    positions: 40,
    description:
      "Pekerja lini perakitan di pabrik Panasonic. Perakitan komponen elektronik dengan standar Jepang.",
    qualifications: [
      "SMK Teknik/Umum",
      "Usia 18–30 tahun",
      "JLPT N5 atau pelatihan",
    ],
    benefits: [
      "Gaji ¥170,000–230,000/bulan",
      "Asrama pabrik",
      "Bonus tahunan",
    ],
    isFunded: false,
    mpChannel: "zenius",
    skillRequirements: [
      { skillName: "Basic Thinking Skills", requiredLevel: 55, userLevel: 45 },
      {
        skillName: "Productivity and Management Skills",
        requiredLevel: 65,
        userLevel: 55,
      },
    ],
    isJobFair: true,
    jobFairEventId: "jf-2025-q1",
  },
  {
    id: "job-020",
    title: "Waiter/Waitress",
    company: "Burj Al Arab",
    offTaker: "APJATI",
    country: "UAE",
    countryFlag: "🇦🇪",
    sector: "Hospitality",
    salaryMin: 11000000,
    salaryMax: 16000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-16T00:00:00Z",
    deadline: "2025-05-25T00:00:00Z",
    positions: 12,
    description:
      "Pelayan di restoran hotel 7 bintang Dubai. Layanan fine dining dengan standar internasional.",
    qualifications: [
      "Pengalaman F&B 2+ tahun",
      "Bahasa Inggris fasih",
      "Penampilan rapi",
    ],
    benefits: [
      "Gaji AED 2,000–3,000 + tip",
      "Akomodasi premium",
      "Makan staff",
    ],
    isFunded: true,
    funderName: "Program CSR",
    fundingCoverage: "Sertifikasi (Rp 3.500.000)",
    mpChannel: "zenius",
    skillRequirements: [
      {
        skillName: "Communication in Japanese/Korean/English",
        requiredLevel: 85,
        userLevel: 20,
      },
      {
        skillName: "Understanding and Be Effective with Others",
        requiredLevel: 80,
        userLevel: 60,
      },
    ],
    isJobFair: false,
  },
];

export const MARKETING_PARTNERS: MarketingPartner[] = [
  {
    id: "mp-zenius",
    name: "Zenius",
    slug: "zenius",
    tagline: "Belajar cerdas, karir global. Zenius × #KaburPortal.",
    color: "#E4002B",
    referralCount: 5420,
    activeJobCount: 38,
  },
  {
    id: "mp-telkomsel",
    name: "Telkomsel",
    slug: "telkomsel",
    tagline: "Koneksi terbaik untuk masa depan PMI Indonesia.",
    color: "#E4002B",
    referralCount: 4980,
    activeJobCount: 52,
  },
];

export const JOB_FAIR_EVENT = {
  id: "jf-2025-q1",
  name: "Job Fair Internasional Q1 2025",
  startDate: "2025-04-15T09:00:00Z",
  endDate: "2025-04-17T17:00:00Z",
  isUpcoming: true,
  employerCount: 38,
  positionCount: 240,
  employers: [
    {
      id: "emp-001",
      name: "Sakura Care Group",
      country: "Jepang",
      countryFlag: "🇯🇵",
      sector: "Care Worker",
      isFunded: true,
      jobCount: 3,
      jobTitles: ["Caregiver Lansia (Kaigo)", "Caregiver Anak", "Nurse Assistant"],
      description:
        "Sakura Care Group adalah jaringan fasilitas perawatan terbesar di Tokyo dan Osaka, telah beroperasi sejak 1992. Kami mempekerjakan lebih dari 800 pekerja migran dari Asia Tenggara dan berkomitmen pada kesejahteraan karyawan internasional.",
      jobIds: ["job-001", "job-008"],
    },
    {
      id: "emp-002",
      name: "Toyota Manufacturing Japan",
      country: "Jepang",
      countryFlag: "🇯🇵",
      sector: "Manufacturing",
      isFunded: false,
      jobCount: 4,
      jobTitles: ["Operator Produksi", "Quality Control Inspector", "Forklift Operator", "Assembly Line Worker"],
      description:
        "Toyota Manufacturing membuka jalur rekrutmen resmi SSW untuk PMI berpengalaman di bidang manufaktur otomotif. Fasilitas produksi kelas dunia di Aichi dan Osaka menawarkan pengalaman kerja yang tidak tertandingi.",
      jobIds: ["job-002"],
    },
    {
      id: "emp-003",
      name: "Jumeirah Group Dubai",
      country: "UAE",
      countryFlag: "🇦🇪",
      sector: "Hospitality",
      isFunded: true,
      jobCount: 5,
      jobTitles: ["Barista & F&B Crew", "Room Attendant", "Waiter/Waitress", "Kitchen Helper", "Housekeeping Supervisor"],
      description:
        "Jumeirah Group adalah operator hotel mewah premium di Dubai. Dengan standar hospitality tertinggi di dunia, kami menawarkan lingkungan kerja internasional, pelatihan kelas dunia, dan jenjang karir yang jelas bagi PMI berbakat.",
      jobIds: ["job-005"],
    },
    {
      id: "emp-004",
      name: "Al Habtoor Construction",
      country: "UAE",
      countryFlag: "🇦🇪",
      sector: "Construction",
      isFunded: false,
      jobCount: 6,
      jobTitles: ["Formwork Carpenter", "Steel Fixer", "Mason", "Plumber", "Electrician", "Safety Officer"],
      description:
        "Al Habtoor Group adalah konglomerat UAE terkemuka di bidang konstruksi mega proyek. Saat ini mengerjakan lebih dari 12 proyek senilai $2 miliar di seluruh UAE dan membutuhkan tenaga kerja terampil dari Indonesia.",
      jobIds: ["job-006"],
    },
  ],
};

export const PAST_JOB_FAIRS = [
  {
    id: "jf-2024-q3",
    name: "Job Fair Internasional Q3 2024",
    startDate: "2024-10-10",
    endDate: "2024-10-12",
    employerCount: 32,
    positionCount: 187,
    placedCount: 68,
  },
  {
    id: "jf-2024-q1",
    name: "Job Fair Internasional Q1 2024",
    startDate: "2024-04-08",
    endDate: "2024-04-10",
    employerCount: 28,
    positionCount: 154,
    placedCount: 52,
  },
];
