import type { Job, MarketingPartner } from "@/types";

export const JOBS: Job[] = [
  {
    id: "job_001",
    title: "Perawat Anak Berkebutuhan Khusus (Fachkraft für Autismus-Betreuung)",
    company: "Vivantes Klinikum Neukölln",
    offTaker: "BINAWAN",
    country: "Germany",
    countryFlag: "🇩🇪",
    sector: "Healthcare",
    salaryMin: 25000000,
    salaryMax: 33000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-01T00:00:00Z",
    deadline: "2025-06-30T00:00:00Z",
    positions: 15,
    description:
      "Provide specialized care and therapeutic support for children diagnosed with Autism Spectrum Disorder (ASD) in residential and day-care settings. Collaborate with multidisciplinary teams including therapists, educators, and families to develop individualized care plans that promote social, emotional, and cognitive development.",
    qualifications: [
      "Male / Female",
      "Age 22–32 years old",
      "Minimum Diploma III (D3) in Nursing or Special Education",
      "Experience working with children with special needs preferred",
      "Minimum German language proficiency level B1",
      "Patient, empathetic, and adaptable personality",
    ],
    benefits: [
      "Sponsored language training up to B2",
      "Accommodation provided for the first 12 months",
      "Pathway to permanent residency (Niederlassungserlaubnis)",
      "Annual flight allowance to home country",
      "Specialized training in ASD care methodology",
    ],
    isFunded: true,
    funderName: "Bundesagentur für Arbeit (German Federal Employment Agency)",
    mpChannel: "zenius",
    skillRequirements: [
      { skillName: "Basic Thinking Skills", requiredLevel: 70, userLevel: 45 },
      { skillName: "Understanding and Be Effective with Others", requiredLevel: 85, userLevel: 60 },
      { skillName: "Communication in Japanese/Korean/English", requiredLevel: 60, userLevel: 20 },
      { skillName: "Productivity and Management Skills", requiredLevel: 55, userLevel: 55 },
    ],
    employerInfo:
      "Vivantes is Berlin's largest municipal hospital group, operating 9 hospitals and over 100 outpatient facilities across the city. With more than 17,000 employees, Vivantes is one of the biggest employers in the German healthcare sector and a leader in pediatric and specialized care services.",
    placement: { city: "Berlin", state: "Berlin", country: "Germany" },
    termsAndConditions: {
      durationOfContract: "24 bulan (perpanjangan berdasarkan evaluasi)",
      annualLeave: "30 hari kerja/tahun",
      probationPeriod: "6 bulan",
      workingDays: "Senin–Jumat (occasional weekend shifts)",
      workingHours: "38.5 jam/minggu",
    },
    documentRequirements: [
      "Paspor", "CV Candidate", "Ijazah", "Transkrip Nilai",
      "Surat Pengalaman Kerja", "BPJS", "Akta Kelahiran",
      "Kartu Tanda Penduduk", "Kartu Keluarga",
      "Surat Izin Orang Tua (jika < 21 tahun)",
    ],
    requiredSubcourses: [
      "Deutsch A1", "Deutsch A2", "Deutsch B1",
      "Komunikasi dengan Pasien dan Keluarga", "Dasar Istilah Medis",
      "Perawatan Anak Berkebutuhan Khusus", "Dokumentasi Perawatan Anak",
      "Psikologi Perkembangan Anak Dasar", "Keselamatan dan Pertolongan Pertama",
      "Komunikasi Terapeutik",
    ],
  },
  {
    id: "job_002",
    title: "Perawat ICU (Intensivpfleger/in)",
    company: "Klinikum rechts der Isar – Technische Universität München",
    offTaker: "APJATI",
    country: "Germany",
    countryFlag: "🇩🇪",
    sector: "Healthcare",
    salaryMin: 28000000,
    salaryMax: 36000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-03T00:00:00Z",
    deadline: "2025-06-30T00:00:00Z",
    positions: 10,
    description:
      "Deliver critical care nursing in the Intensive Care Unit of a leading German hospital. Monitor and manage patients with life-threatening conditions, operate advanced medical equipment, administer medications, and coordinate with physicians and specialists to ensure optimal patient outcomes in high-acuity settings.",
    qualifications: [
      "Male / Female",
      "Age 24–35 years old",
      "Minimum Bachelor's Degree (S1) in Nursing",
      "Active STR (Surat Tanda Registrasi Keperawatan)",
      "Minimum 2 years of ICU or emergency room experience",
      "Minimum German language proficiency level B1",
      "BLS and ACLS certification preferred",
    ],
    benefits: [
      "Sponsored language training up to B2",
      "Relocation package including accommodation for 6 months",
      "Pathway to permanent residency (Niederlassungserlaubnis)",
      "Annual flight allowance to home country",
      "Access to advanced ICU training and certifications in Germany",
      "Competitive salary with night shift and weekend premiums",
    ],
    isFunded: true,
    funderName: "GIZ (Deutsche Gesellschaft für Internationale Zusammenarbeit) — Triple Win Programme",
    mpChannel: "telkomsel",
    skillRequirements: [
      { skillName: "Basic Thinking Skills", requiredLevel: 75, userLevel: 45 },
      { skillName: "Understanding and Be Effective with Others", requiredLevel: 80, userLevel: 60 },
      { skillName: "Communication in Japanese/Korean/English", requiredLevel: 65, userLevel: 20 },
      { skillName: "Productivity and Management Skills", requiredLevel: 70, userLevel: 55 },
    ],
    employerInfo:
      "One of Germany's top-ranked university hospitals affiliated with the Technical University of Munich. The hospital operates over 1,100 beds across 33 specialized departments and is recognized as a center of excellence in intensive care, surgical innovation, and translational medicine.",
    placement: { city: "Munich", state: "Bavaria", country: "Germany" },
    termsAndConditions: {
      durationOfContract: "36 bulan (perpanjangan berdasarkan evaluasi)",
      annualLeave: "30 hari kerja/tahun",
      probationPeriod: "6 bulan",
      workingDays: "Senin–Minggu (shift system, termasuk malam)",
      workingHours: "38.5 jam/minggu",
    },
    documentRequirements: [
      "Paspor", "CV Candidate", "Ijazah", "Transkrip Nilai",
      "Surat Tanda Registrasi Keperawatan", "Surat Pengalaman Kerja",
      "BPJS", "Akta Kelahiran", "Kartu Tanda Penduduk", "Kartu Keluarga",
    ],
    requiredSubcourses: [
      "Deutsch A1", "Deutsch A2", "Deutsch B1",
      "Komunikasi dengan Pasien", "Dasar Istilah Medis",
      "Dokumentasi di Rumah Sakit", "Istilah Perawatan Intensif",
      "Komunikasi Darurat Medis", "Pengoperasian Alat Medis",
      "Farmakologi Dasar", "Etika dan Hukum Keperawatan",
    ],
  },
  {
    id: "job_003",
    title: "Perawat Geriatri (Altenpfleger/in im Krankenhaus)",
    company: "Evangelisches Krankenhaus Düsseldorf",
    offTaker: "BINAWAN",
    country: "Germany",
    countryFlag: "🇩🇪",
    sector: "Healthcare",
    salaryMin: 23000000,
    salaryMax: 30000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-05T00:00:00Z",
    deadline: "2025-06-30T00:00:00Z",
    positions: 20,
    description:
      "Provide compassionate and skilled nursing care to elderly patients in hospital geriatric wards and long-term care facilities. Manage chronic conditions, assist with rehabilitation programs, coordinate medication schedules, and support patients in maintaining dignity and quality of life throughout their care journey.",
    qualifications: [
      "Male / Female",
      "Age 22–35 years old",
      "Minimum Diploma III (D3) in Nursing",
      "Active STR (Surat Tanda Registrasi Keperawatan)",
      "Minimum 1 year of clinical or elderly care experience",
      "Minimum German language proficiency level B1",
      "Compassionate and patient demeanor",
    ],
    benefits: [
      "Sponsored language training up to B2",
      "Accommodation support for the first 6 months",
      "Pathway to permanent residency (Niederlassungserlaubnis)",
      "Annual flight allowance to home country",
      "Free meals during working shifts",
      "Geriatric care specialization training",
    ],
    isFunded: false,
    skillRequirements: [
      { skillName: "Basic Thinking Skills", requiredLevel: 65, userLevel: 45 },
      { skillName: "Understanding and Be Effective with Others", requiredLevel: 80, userLevel: 60 },
      { skillName: "Communication in Japanese/Korean/English", requiredLevel: 60, userLevel: 20 },
    ],
    employerInfo:
      "A well-established Protestant hospital in Düsseldorf with over 120 years of history. Operates 450 beds specializing in internal medicine, geriatric care, and palliative medicine. Known for its patient-centered approach and strong commitment to elderly care and rehabilitation services.",
    placement: { city: "Düsseldorf", state: "North Rhine-Westphalia", country: "Germany" },
    termsAndConditions: {
      durationOfContract: "24 bulan (perpanjangan berdasarkan evaluasi)",
      annualLeave: "30 hari kerja/tahun",
      probationPeriod: "6 bulan",
      workingDays: "Senin–Minggu (shift system)",
      workingHours: "38.5 jam/minggu",
    },
    documentRequirements: [
      "Paspor", "CV Candidate", "Ijazah", "Transkrip Nilai",
      "Surat Tanda Registrasi Keperawatan", "Surat Pengalaman Kerja",
      "BPJS", "Akta Kelahiran", "Kartu Tanda Penduduk", "Kartu Keluarga",
      "Surat Izin Orang Tua (jika < 21 tahun)",
    ],
    requiredSubcourses: [
      "Deutsch A1", "Deutsch A2", "Deutsch B1",
      "Komunikasi dengan Pasien dan Keluarga", "Dasar Istilah Medis",
      "Dokumentasi di Rumah Sakit", "Perawatan Lansia dan Rehabilitasi",
      "Manajemen Penyakit Kronis", "Nutrisi dan Diet untuk Lansia",
      "Pertolongan Pertama dan Penanganan Darurat",
    ],
  },
  {
    id: "job_004",
    title: "Pengukir Kayu Tradisional (Holzbildhauer/in)",
    company: "Schnitzwerkstatt Lang",
    offTaker: "Mitra Kerja Nusantara",
    country: "Germany",
    countryFlag: "🇩🇪",
    sector: "Manufacturing",
    salaryMin: 18000000,
    salaryMax: 24000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-07T00:00:00Z",
    deadline: "2025-06-30T00:00:00Z",
    positions: 8,
    description:
      "Create and restore intricate wood carvings, sculptures, and ornamental works for architectural restoration, religious institutions, and luxury interior projects across Bavaria. Work with traditional European woodworking techniques alongside master artisans, preserving centuries-old craftsmanship while incorporating contemporary design sensibilities.",
    qualifications: [
      "Male / Female",
      "Age 20–40 years old",
      "Minimum SMK or vocational training in woodworking, fine arts, or related craft",
      "Portfolio of woodcarving or sculpture work required",
      "Minimum 2 years of hands-on woodcarving experience",
      "Minimum German language proficiency level A2",
      "Strong attention to detail and artistic sensibility",
    ],
    benefits: [
      "Apprenticeship under certified German master woodcarvers (Meister)",
      "Sponsored language training up to B1",
      "Accommodation provided near workshop",
      "Tools and materials provided",
      "Opportunity to obtain German craftsman certification (Gesellenbrief)",
      "Annual flight allowance to home country",
    ],
    isFunded: true,
    funderName: "Bayerisches Staatsministerium für Wissenschaft und Kunst",
    skillRequirements: [
      { skillName: "Basic Thinking Skills", requiredLevel: 65, userLevel: 45 },
      { skillName: "Basic Decision-Making", requiredLevel: 60, userLevel: 30 },
      { skillName: "Productivity and Management Skills", requiredLevel: 65, userLevel: 55 },
    ],
    employerInfo:
      "A family-run woodcarving workshop in Oberammergau with over 80 years of tradition. Specializes in religious sculptures, architectural ornaments, and bespoke art commissions. Oberammergau is world-renowned for its woodcarving heritage and the workshop is one of the last in the region training international apprentices.",
    placement: { city: "Oberammergau", state: "Bavaria", country: "Germany" },
    termsAndConditions: {
      durationOfContract: "36 bulan (termasuk masa pelatihan)",
      annualLeave: "24 hari kerja/tahun",
      probationPeriod: "3 bulan",
      workingDays: "Senin–Jumat",
      workingHours: "40 jam/minggu",
    },
    documentRequirements: [
      "Paspor", "CV Candidate", "Resume", "Ijazah", "Transkrip Nilai",
      "Surat Pengalaman Kerja", "Akta Kelahiran", "Kartu Tanda Penduduk",
      "Kartu Keluarga", "Surat Izin Orang Tua (jika < 21 tahun)",
    ],
    requiredSubcourses: [
      "Deutsch A1", "Deutsch A2",
      "Teknik Ukir dan Pahat Kayu", "Jenis Kayu dan Karakteristiknya",
      "Membaca Gambar Desain dan Pola", "Keselamatan Kerja di Bengkel",
      "Alat Tangan dan Alat Mesin Kayu", "Finishing dan Pengawetan Kayu",
      "Sejarah Seni Ukir Eropa",
    ],
  },
  {
    id: "job_005",
    title: "Kru Kabin (Flugbegleiter/in)",
    company: "Condor Flugdienst GmbH",
    offTaker: "APJATI",
    country: "Germany",
    countryFlag: "🇩🇪",
    sector: "Hospitality",
    salaryMin: 20000000,
    salaryMax: 28000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-08T00:00:00Z",
    deadline: "2025-07-31T00:00:00Z",
    positions: 25,
    description:
      "Ensure the safety, comfort, and satisfaction of passengers aboard short-haul and long-haul flights. Conduct pre-flight safety checks, deliver in-flight service, manage onboard emergencies, and represent the airline's brand with professionalism and warmth. Operate from Frankfurt hub with routes across Europe, Asia, and the Americas.",
    qualifications: [
      "Female / Male",
      "Age 21–30 years old",
      "Minimum Diploma III (D3) in any field",
      "Minimum height 160cm (female) / 170cm (male)",
      "Fluent in English (TOEIC 700+ or equivalent)",
      "Minimum German language proficiency level A2",
      "Excellent grooming and interpersonal skills",
      "Able to swim minimum 25 meters unassisted",
    ],
    benefits: [
      "Sponsored cabin crew training program (8 weeks)",
      "Sponsored language training up to B1",
      "Discounted flight tickets for employee and family",
      "Layover allowances in international destinations",
      "Health and dental insurance",
      "Accommodation support during initial training period",
    ],
    isFunded: false,
    mpChannel: "zenius",
    skillRequirements: [
      { skillName: "Communication in Japanese/Korean/English", requiredLevel: 80, userLevel: 20 },
      { skillName: "Understanding and Be Effective with Others", requiredLevel: 85, userLevel: 60 },
      { skillName: "Productivity and Management Skills", requiredLevel: 65, userLevel: 55 },
    ],
    employerInfo:
      "Condor is a leading German leisure airline headquartered in Frankfurt. Operating since 1956, the airline serves over 90 destinations worldwide with a fleet of modern Airbus A320neo and A330neo aircraft. Condor carries approximately 9 million passengers annually and is known for its diverse, multilingual cabin crew.",
    placement: { city: "Frankfurt", state: "Hesse", country: "Germany" },
    termsAndConditions: {
      durationOfContract: "36 bulan (perpanjangan berdasarkan evaluasi)",
      annualLeave: "28 hari kerja/tahun",
      probationPeriod: "6 bulan",
      workingDays: "Shift system (termasuk weekend dan hari libur)",
      workingHours: "Rata-rata 35–40 jam/minggu (variabel berdasarkan jadwal penerbangan)",
    },
    documentRequirements: [
      "Paspor", "CV Candidate", "Cover Letter", "Ijazah", "Transkrip Nilai",
      "BPJS", "Akta Kelahiran", "Kartu Tanda Penduduk", "Kartu Keluarga",
      "Surat Izin Orang Tua (jika < 21 tahun)",
    ],
    requiredSubcourses: [
      "Deutsch A1", "Deutsch A2",
      "Pelayanan Penumpang dan Keramahan", "Prosedur Keselamatan Penerbangan",
      "Penanganan Keluhan Penumpang", "Makanan dan Minuman dalam Penerbangan",
      "Pertolongan Pertama di Pesawat", "Komunikasi Antar Kru",
      "Penanganan Situasi Darurat",
    ],
  },
  {
    id: "job_006",
    title: "Pengemudi Bus & Truk (Bus- und LKW-Fahrer/in)",
    company: "Hamburger Hochbahn AG",
    offTaker: "Mitra Kerja Nusantara",
    country: "Germany",
    countryFlag: "🇩🇪",
    sector: "Transportation",
    salaryMin: 22000000,
    salaryMax: 28000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-09T00:00:00Z",
    deadline: "2025-07-31T00:00:00Z",
    positions: 30,
    description:
      "Operate commercial buses and heavy goods vehicles across Hamburg's metropolitan transit network and regional logistics routes. Ensure safe and timely transportation of passengers or cargo, perform vehicle inspections, maintain compliance with European driving regulations, and deliver excellent service to passengers and logistics partners.",
    qualifications: [
      "Male / Female",
      "Age 23–40 years old",
      "Minimum SMA/SMK or equivalent",
      "Valid SIM B2 Umum (Indonesian commercial driving license)",
      "Minimum 2 years of professional driving experience (bus or truck)",
      "Minimum German language proficiency level A2",
      "Clean driving record with no major violations",
      "Physically fit with valid medical certificate",
    ],
    benefits: [
      "Sponsored EU commercial driving license conversion (Führerschein Klasse C/D)",
      "Sponsored language training up to B1",
      "Accommodation support for the first 6 months",
      "Overtime and holiday pay premiums",
      "Health insurance included",
      "Annual flight allowance to home country",
    ],
    isFunded: true,
    funderName: "Hamburger Hochbahn AG (employer-funded training program)",
    mpChannel: "telkomsel",
    skillRequirements: [
      { skillName: "Basic Thinking Skills", requiredLevel: 60, userLevel: 45 },
      { skillName: "Basic Decision-Making", requiredLevel: 65, userLevel: 30 },
      { skillName: "Productivity and Management Skills", requiredLevel: 65, userLevel: 55 },
    ],
    employerInfo:
      "Hamburg's primary public transit operator, managing the city's bus and U-Bahn network. Hochbahn transports over 1.2 million passengers daily and operates a fleet of 1,000+ buses across 112 routes. The company is actively recruiting international drivers to meet growing urban mobility demands.",
    placement: { city: "Hamburg", state: "Hamburg", country: "Germany" },
    termsAndConditions: {
      durationOfContract: "24 bulan (perpanjangan berdasarkan evaluasi)",
      annualLeave: "26 hari kerja/tahun",
      probationPeriod: "3 bulan",
      workingDays: "Senin–Sabtu (rotasi shift)",
      workingHours: "40 jam/minggu (sesuai regulasi EU driving hours)",
    },
    documentRequirements: [
      "Paspor", "CV Candidate", "Ijazah", "Surat Pengalaman Kerja",
      "BPJS", "Akta Kelahiran", "Kartu Tanda Penduduk", "Kartu Keluarga",
      "Surat Izin Orang Tua (jika < 21 tahun)",
    ],
    requiredSubcourses: [
      "Deutsch A1", "Deutsch A2",
      "Peraturan Lalu Lintas Eropa", "Navigasi dan Pembacaan Peta",
      "Perawatan dan Inspeksi Kendaraan", "Keselamatan Berkendara Komersial",
      "Penanganan Muatan dan Kargo", "Komunikasi dengan Penumpang",
      "Prosedur Darurat di Jalan Raya",
    ],
  },
  {
    id: "job_007",
    title: "Perawat & Bidan RS Pemerintah (Registered Nurse & Midwife)",
    company: "The Royal Women's Hospital Melbourne",
    offTaker: "BINAWAN",
    country: "Australia",
    countryFlag: "🇦🇺",
    sector: "Healthcare",
    salaryMin: 28000000,
    salaryMax: 38000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-05T00:00:00Z",
    deadline: "2025-07-31T00:00:00Z",
    positions: 20,
    description:
      "Deliver comprehensive nursing and midwifery care within Australia's public hospital system. Manage patient assessments, administer treatments, support maternity care from prenatal through postnatal stages, and contribute to community health initiatives. Work within a multicultural healthcare environment serving diverse patient populations.",
    qualifications: [
      "Male / Female",
      "Age 22–35 years old",
      "Minimum Bachelor's Degree (S1) in Nursing or Midwifery",
      "Active STR (Surat Tanda Registrasi Keperawatan) or equivalent",
      "Minimum 1 year of clinical experience",
      "Minimum IELTS score of 7.0 (or OET Grade B)",
      "Willingness to complete AHPRA registration process",
    ],
    benefits: [
      "Sponsored AHPRA registration and bridging program",
      "Relocation assistance up to AUD 5,000",
      "Pathway to permanent residency via employer-sponsored visa (subclass 482/186)",
      "Salary packaging and tax benefits",
      "Paid professional development and continuing education",
      "Superannuation (retirement fund) contributions",
    ],
    isFunded: true,
    funderName: "Victorian Department of Health — International Nurse Recruitment Program",
    mpChannel: "zenius",
    skillRequirements: [
      { skillName: "Basic Thinking Skills", requiredLevel: 70, userLevel: 45 },
      { skillName: "Understanding and Be Effective with Others", requiredLevel: 80, userLevel: 60 },
      { skillName: "Communication in Japanese/Korean/English", requiredLevel: 75, userLevel: 20 },
    ],
    employerInfo:
      "Australia's largest specialist hospital for women's health, neonatal care, and maternity services. Located in Parkville, the hospital delivers over 7,500 babies annually and provides care across gynaecology, oncology, and neonatal intensive care. Affiliated with the University of Melbourne and a teaching hospital with a strong international workforce.",
    placement: { city: "Melbourne", state: "Victoria", country: "Australia" },
    termsAndConditions: {
      durationOfContract: "24 bulan (perpanjangan berdasarkan evaluasi)",
      annualLeave: "20 hari kerja/tahun + 10 personal/sick leave",
      probationPeriod: "6 bulan",
      workingDays: "Senin–Minggu (shift system)",
      workingHours: "38 jam/minggu",
    },
    documentRequirements: [
      "Paspor", "CV Candidate", "Cover Letter", "Resume", "Ijazah", "Transkrip Nilai",
      "Surat Tanda Registrasi Keperawatan", "Surat Pengalaman Kerja",
      "BPJS", "Akta Kelahiran", "Kartu Tanda Penduduk", "Kartu Keluarga",
    ],
    requiredSubcourses: [
      "English Beginner", "English Intermediate", "English Advanced",
      "Komunikasi dengan Pasien Multikultural", "Istilah Medis dalam Bahasa Inggris",
      "Dokumentasi Klinis", "Perawatan Prenatal dan Postnatal",
      "Penulisan Laporan Medis", "Etika Keperawatan Internasional",
      "Kebidanan dan Kesehatan Ibu",
    ],
  },
  {
    id: "job_008",
    title: "Profesional Perhotelan & F&B (Hospitality Professional)",
    company: "Merivale Group",
    offTaker: "APJATI",
    country: "Australia",
    countryFlag: "🇦🇺",
    sector: "Hospitality",
    salaryMin: 22000000,
    salaryMax: 30000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-06T00:00:00Z",
    deadline: "2025-07-31T00:00:00Z",
    positions: 25,
    description:
      "Join a premium hospitality team at one of Sydney's top-rated hotels and restaurants. Deliver exceptional guest experiences across front-of-house operations, food and beverage service, event coordination, and guest relations. Work in a fast-paced, multicultural environment catering to international travelers and high-profile clientele.",
    qualifications: [
      "Male / Female",
      "Age 21–30 years old",
      "Minimum Diploma III (D3) in Hospitality, Tourism, or Culinary Arts",
      "Minimum 1 year of experience in hotels, restaurants, or event management",
      "Minimum IELTS score of 5.5 (or equivalent)",
      "Excellent presentation and communication skills",
      "RSA (Responsible Service of Alcohol) certification preferred",
    ],
    benefits: [
      "Sponsored RSA and food safety certification",
      "Accommodation assistance for the first 3 months",
      "Pathway to permanent residency via employer-sponsored visa",
      "Discounted hotel stays across partner properties",
      "Tips and service charge sharing",
      "Career progression to supervisory and management roles",
    ],
    isFunded: false,
    skillRequirements: [
      { skillName: "Communication in Japanese/Korean/English", requiredLevel: 70, userLevel: 20 },
      { skillName: "Understanding and Be Effective with Others", requiredLevel: 80, userLevel: 60 },
      { skillName: "Productivity and Management Skills", requiredLevel: 65, userLevel: 55 },
    ],
    employerInfo:
      "One of Australia's largest privately owned hospitality groups, operating over 80 venues across Sydney including award-winning restaurants, bars, hotels, and event spaces. Merivale employs over 5,000 staff and is a dominant force in Sydney's dining and nightlife scene, known for brands like Mr. Wong, Ivy, and Hotel Centennial.",
    placement: { city: "Sydney", state: "New South Wales", country: "Australia" },
    termsAndConditions: {
      durationOfContract: "24 bulan (perpanjangan berdasarkan evaluasi)",
      annualLeave: "20 hari kerja/tahun + 10 personal/sick leave",
      probationPeriod: "3 bulan",
      workingDays: "Senin–Minggu (shift system, termasuk hari libur)",
      workingHours: "38 jam/minggu",
    },
    documentRequirements: [
      "Paspor", "CV Candidate", "Cover Letter", "Ijazah", "Transkrip Nilai",
      "Surat Pengalaman Kerja", "Akta Kelahiran", "Kartu Tanda Penduduk",
      "Kartu Keluarga", "Surat Izin Orang Tua (jika < 21 tahun)",
    ],
    requiredSubcourses: [
      "English Beginner", "English Intermediate",
      "Pelayanan Tamu dan Keramahan", "Penanganan Keluhan Tamu",
      "Makanan dan Minuman Internasional", "Koordinasi Acara dan Reservasi",
      "Kebersihan dan Keamanan Pangan", "Manajemen Restoran dan Bar",
      "Etika Kerja di Industri Perhotelan",
    ],
  },
  {
    id: "job_009",
    title: "Juru Gambar Arsitektur (Bautechnische/r Zeichner/in)",
    company: "Architekten Maurer & Partner ZT GmbH",
    offTaker: "Mitra Kerja Nusantara",
    country: "Austria",
    countryFlag: "🇦🇹",
    sector: "Construction",
    salaryMin: 22000000,
    salaryMax: 28000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-08T00:00:00Z",
    deadline: "2025-07-31T00:00:00Z",
    positions: 10,
    description:
      "Produce detailed architectural and construction drawings for residential, commercial, and public infrastructure projects across Vienna. Translate design concepts from architects and engineers into precise technical drawings using CAD software. Collaborate with project teams on building permit documentation, construction detailing, and 3D visualization.",
    qualifications: [
      "Male / Female",
      "Age 22–35 years old",
      "Minimum Diploma III (D3) or Bachelor's Degree in Architecture, Civil Engineering, or Drafting",
      "Proficient in AutoCAD, Revit, or ArchiCAD",
      "Portfolio of technical/architectural drawings required",
      "Minimum 1 year of drafting experience",
      "Minimum German language proficiency level A2",
      "Strong spatial reasoning and attention to detail",
    ],
    benefits: [
      "Sponsored language training up to B1",
      "Relocation support including accommodation for the first 3 months",
      "Access to Austrian architecture and construction certification programs",
      "Public transportation pass (Wiener Linien Jahreskarte)",
      "Pathway to Red-White-Red Card (Austrian work permit)",
      "Annual flight allowance to home country",
    ],
    isFunded: true,
    funderName: "AMS Österreich (Austrian Public Employment Service) — Fachkräfteoffensive",
    mpChannel: "telkomsel",
    skillRequirements: [
      { skillName: "Basic Thinking Skills", requiredLevel: 70, userLevel: 45 },
      { skillName: "Basic Decision-Making", requiredLevel: 65, userLevel: 30 },
      { skillName: "Productivity and Management Skills", requiredLevel: 70, userLevel: 55 },
    ],
    employerInfo:
      "A mid-sized architecture and engineering firm based in Vienna's 7th district, specializing in urban residential development, public infrastructure, and heritage building restoration. The firm has delivered over 200 projects across Austria and Central Europe and is known for combining traditional Viennese architectural aesthetics with modern sustainable design.",
    placement: { city: "Vienna", state: "Vienna", country: "Austria" },
    termsAndConditions: {
      durationOfContract: "24 bulan (perpanjangan berdasarkan evaluasi)",
      annualLeave: "25 hari kerja/tahun",
      probationPeriod: "3 bulan",
      workingDays: "Senin–Jumat",
      workingHours: "38.5 jam/minggu",
    },
    documentRequirements: [
      "Paspor", "CV Candidate", "Cover Letter", "Resume", "Ijazah", "Transkrip Nilai",
      "Surat Pengalaman Kerja", "Akta Kelahiran", "Kartu Tanda Penduduk", "Kartu Keluarga",
    ],
    requiredSubcourses: [
      "Deutsch A1", "Deutsch A2",
      "Membaca dan Membuat Gambar Teknis", "Istilah Teknis Bangunan dan Konstruksi",
      "Penggunaan CAD untuk Arsitektur", "Standar Bangunan dan Regulasi Eropa",
      "Komunikasi dalam Tim Proyek", "Material Bangunan dan Spesifikasinya",
      "Dasar Perencanaan Tata Ruang", "Pemodelan 3D dan Visualisasi",
    ],
  },
  {
    id: "job_010",
    title: "Pembuat Pastry & Cokelat (Konditor/in)",
    company: "Confiserie Sprüngli AG",
    offTaker: "BINAWAN",
    country: "Switzerland",
    countryFlag: "🇨🇭",
    sector: "Hospitality",
    salaryMin: 24000000,
    salaryMax: 32000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-09T00:00:00Z",
    deadline: "2025-07-31T00:00:00Z",
    positions: 8,
    description:
      "Craft premium Swiss pastries, chocolates, confections, and baked goods at a renowned pâtisserie and chocolatier in Zürich. Master traditional Swiss and European confectionery techniques, create seasonal collections, and contribute to product innovation. Work alongside award-winning pastry chefs in one of the world's most celebrated culinary destinations.",
    qualifications: [
      "Male / Female",
      "Age 20–35 years old",
      "Minimum SMK or vocational training in Pastry, Bakery, or Culinary Arts",
      "Minimum 1 year of professional pastry or bakery experience",
      "Portfolio or documentation of past creations preferred",
      "Minimum German language proficiency level A2",
      "Creative, detail-oriented, and able to work under pressure",
    ],
    benefits: [
      "Apprenticeship under certified Swiss master confectioners",
      "Sponsored language training up to B1",
      "Accommodation provided near workplace",
      "Meals provided during working shifts",
      "Opportunity to obtain Swiss Federal Certificate of Proficiency (EFZ)",
      "Discounts on premium Swiss chocolate and pastry products",
      "Annual flight allowance to home country",
    ],
    isFunded: true,
    funderName: "Sprüngli Foundation — Apprenticeship & Cultural Exchange Fund",
    skillRequirements: [
      { skillName: "Basic Thinking Skills", requiredLevel: 65, userLevel: 45 },
      { skillName: "Productivity and Management Skills", requiredLevel: 70, userLevel: 55 },
      { skillName: "Understanding and Be Effective with Others", requiredLevel: 70, userLevel: 60 },
    ],
    employerInfo:
      "One of Switzerland's oldest and most prestigious confectioners, founded in 1836. Famous worldwide for its Luxemburgerli macarons and handcrafted Swiss chocolates. Sprüngli operates 25 locations across Switzerland and maintains its own production facility in Dietikon. The company has a long-standing tradition of training international apprentices in Swiss confectionery arts.",
    placement: { city: "Zürich", state: "Zürich", country: "Switzerland" },
    termsAndConditions: {
      durationOfContract: "36 bulan (termasuk masa pelatihan)",
      annualLeave: "20 hari kerja/tahun",
      probationPeriod: "3 bulan",
      workingDays: "Senin–Sabtu (1 hari libur di weekday sebagai pengganti)",
      workingHours: "42 jam/minggu",
    },
    documentRequirements: [
      "Paspor", "CV Candidate", "Ijazah", "Transkrip Nilai",
      "Surat Pengalaman Kerja", "Akta Kelahiran", "Kartu Tanda Penduduk",
      "Kartu Keluarga", "Surat Izin Orang Tua (jika < 21 tahun)",
    ],
    requiredSubcourses: [
      "Deutsch A1", "Deutsch A2",
      "Teknik Pembuatan Pastry Eropa", "Teknik Pengolahan Cokelat",
      "Kebersihan dan Keamanan Pangan", "Resep dan Konversi Takaran",
      "Dekorasi dan Plating", "Manajemen Dapur dan Inventaris",
      "Pengenalan Bahan Baku Premium", "Inovasi Produk dan Menu Musiman",
    ],
  },
  {
    id: "job_011",
    title: "Perawat Rumah Sakit (病院看護師)",
    company: "St. Luke's International Hospital (聖路加国際病院)",
    offTaker: "APJATI",
    country: "Japan",
    countryFlag: "🇯🇵",
    sector: "Healthcare",
    salaryMin: 16000000,
    salaryMax: 24000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-04T00:00:00Z",
    deadline: "2025-06-30T00:00:00Z",
    positions: 15,
    description:
      "Provide comprehensive nursing care in one of Tokyo's leading medical institutions. Perform patient assessments, administer medications and treatments, assist physicians during procedures, and ensure accurate medical documentation. Work within Japan's advanced healthcare system while supporting international patient services.",
    qualifications: [
      "Male / Female",
      "Age 22–35 years old",
      "Minimum Bachelor's Degree (S1) in Nursing",
      "Active STR (Surat Tanda Registrasi Keperawatan)",
      "Minimum 1 year of clinical experience",
      "Minimum Japanese language proficiency level JLPT N3",
      "Willingness to obtain Japanese nursing license (看護師国家試験)",
    ],
    benefits: [
      "Sponsored Japanese language training up to JLPT N2",
      "Sponsored preparation for Japanese nursing license exam",
      "Accommodation provided for the first 12 months",
      "Pathway to permanent residency via Specified Skilled Worker visa",
      "Annual flight allowance to home country",
      "Bonus for passing Japanese nursing license exam",
    ],
    isFunded: true,
    funderName: "JICWELS (Japan International Corporation of Welfare Services) — EPA Programme",
    mpChannel: "zenius",
    skillRequirements: [
      { skillName: "Basic Thinking Skills", requiredLevel: 70, userLevel: 45 },
      { skillName: "Understanding and Be Effective with Others", requiredLevel: 80, userLevel: 60 },
      { skillName: "Communication in Japanese/Korean/English", requiredLevel: 65, userLevel: 20 },
    ],
    employerInfo:
      "One of Tokyo's most prestigious international hospitals, founded in 1901 and located in Chuo-ku. Operates 520 beds with over 30 medical departments and is renowned for its bilingual medical services. Affiliated with St. Luke's International University and consistently ranked among Japan's top hospitals. Actively recruits international nurses through the EPA (Economic Partnership Agreement) framework.",
    placement: { city: "Tokyo", state: "Tokyo", country: "Japan" },
    termsAndConditions: {
      durationOfContract: "36 bulan (perpanjangan berdasarkan evaluasi dan lisensi)",
      annualLeave: "20 hari kerja/tahun",
      probationPeriod: "6 bulan",
      workingDays: "Senin–Minggu (shift system)",
      workingHours: "40 jam/minggu",
    },
    documentRequirements: [
      "Paspor", "CV Candidate", "Resume", "Ijazah", "Transkrip Nilai",
      "Surat Tanda Registrasi Keperawatan", "Surat Pengalaman Kerja",
      "BPJS", "Akta Kelahiran", "Kartu Tanda Penduduk", "Kartu Keluarga",
    ],
    requiredSubcourses: [
      "Nihongo N5", "Nihongo N4", "Nihongo N3",
      "Komunikasi dengan Pasien Jepang", "Dasar Istilah Medis Jepang",
      "Dokumentasi di Rumah Sakit Jepang", "Sistem Kesehatan dan Asuransi Jepang",
      "Farmakologi Dasar", "Etika Keperawatan di Jepang",
      "Persiapan Ujian Lisensi Keperawatan Jepang",
    ],
  },
  {
    id: "job_012",
    title: "Perawat Fasilitas Lansia (介護福祉士)",
    company: "Seishinkai Medical Group (清心会医療グループ)",
    offTaker: "Mitra Kerja Nusantara",
    country: "Japan",
    countryFlag: "🇯🇵",
    sector: "Care Worker",
    salaryMin: 14000000,
    salaryMax: 20000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-06T00:00:00Z",
    deadline: "2025-06-30T00:00:00Z",
    positions: 20,
    description:
      "Provide dedicated elderly care services at a specialized long-term care facility in Osaka. Assist residents with daily living activities, implement individualized care plans, facilitate recreational and rehabilitation programs, and ensure the physical and emotional well-being of elderly residents in Japan's aging society.",
    qualifications: [
      "Male / Female",
      "Age 21–35 years old",
      "Minimum Diploma III (D3) in Nursing or Caregiving",
      "Experience in elderly care or geriatric nursing preferred",
      "Minimum Japanese language proficiency level JLPT N4",
      "Patient, respectful, and culturally sensitive",
      "Willingness to obtain Kaigo Fukushishi certification",
    ],
    benefits: [
      "Sponsored Japanese language training up to JLPT N3",
      "Sponsored Kaigo Fukushishi exam preparation",
      "Accommodation provided throughout contract period",
      "Meals provided during working shifts",
      "Pathway to permanent residency via Specified Skilled Worker visa",
      "Annual flight allowance to home country",
      "Bonus for passing Kaigo Fukushishi certification exam",
    ],
    isFunded: true,
    funderName: "JICWELS (Japan International Corporation of Welfare Services) — EPA Programme",
    mpChannel: "telkomsel",
    skillRequirements: [
      { skillName: "Understanding and Be Effective with Others", requiredLevel: 85, userLevel: 60 },
      { skillName: "Basic Thinking Skills", requiredLevel: 60, userLevel: 45 },
      { skillName: "Communication in Japanese/Korean/English", requiredLevel: 60, userLevel: 20 },
    ],
    employerInfo:
      "A major elderly care and medical welfare group based in Osaka Prefecture, operating 12 long-term care facilities, 3 rehabilitation centers, and 2 group homes across the Kansai region. Seishinkai serves over 2,000 elderly residents and has been a pioneer in Japan's kaigo workforce internationalization program, hosting Indonesian and Filipino care workers since 2009.",
    placement: { city: "Osaka", state: "Osaka", country: "Japan" },
    termsAndConditions: {
      durationOfContract: "36 bulan (perpanjangan berdasarkan evaluasi dan sertifikasi)",
      annualLeave: "20 hari kerja/tahun",
      probationPeriod: "3 bulan",
      workingDays: "Senin–Minggu (shift system)",
      workingHours: "40 jam/minggu",
    },
    documentRequirements: [
      "Paspor", "CV Candidate", "Ijazah", "Transkrip Nilai",
      "Surat Pengalaman Kerja", "BPJS", "Akta Kelahiran",
      "Kartu Tanda Penduduk", "Kartu Keluarga",
      "Surat Izin Orang Tua (jika < 21 tahun)",
    ],
    requiredSubcourses: [
      "Nihongo N5", "Nihongo N4", "Nihongo N3",
      "Komunikasi dengan Lansia Jepang", "Perawatan Lansia dan Aktivitas Harian",
      "Istilah Perawatan Lansia Jepang", "Rehabilitasi dan Terapi Ringan",
      "Nutrisi dan Diet untuk Lansia", "Dokumentasi Perawatan",
      "Persiapan Ujian Kaigo Fukushishi",
    ],
  },
  {
    id: "job_013",
    title: "Teknisi Otomotif (自動車整備士)",
    company: "Nagoya Toyota Motor Co., Ltd. (名古屋トヨタ自動車株式会社)",
    offTaker: "BINAWAN",
    country: "Japan",
    countryFlag: "🇯🇵",
    sector: "Manufacturing",
    salaryMin: 16000000,
    salaryMax: 22000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-10T00:00:00Z",
    deadline: "2025-06-30T00:00:00Z",
    positions: 12,
    description:
      "Perform diagnostics, maintenance, and repairs on vehicles at an authorized dealership and service center in Japan's automotive heartland. Work with cutting-edge Japanese automotive technology, hybrid and electric vehicle systems, and advanced diagnostic equipment. Contribute to the highest standards of vehicle safety and performance.",
    qualifications: [
      "Male / Female",
      "Age 21–35 years old",
      "Minimum SMK or vocational training in Automotive Engineering or Mechanical Engineering",
      "Minimum 2 years of professional automotive repair experience",
      "Familiarity with Japanese vehicle brands (Toyota, Honda, Nissan, etc.)",
      "Minimum Japanese language proficiency level JLPT N4",
      "Valid Indonesian driving license (SIM A)",
    ],
    benefits: [
      "Sponsored Japanese language training up to JLPT N3",
      "Training on hybrid and EV technology",
      "Accommodation provided for the first 12 months",
      "Tools and work uniforms provided",
      "Pathway to Specified Skilled Worker visa renewal",
      "Annual flight allowance to home country",
      "Opportunity to obtain Japanese automotive mechanic certification",
    ],
    isFunded: false,
    skillRequirements: [
      { skillName: "Basic Decision-Making", requiredLevel: 65, userLevel: 30 },
      { skillName: "Productivity and Management Skills", requiredLevel: 70, userLevel: 55 },
      { skillName: "Basic Thinking Skills", requiredLevel: 65, userLevel: 45 },
    ],
    employerInfo:
      "An authorized Toyota dealer group based in Nagoya, Aichi Prefecture — the hometown of Toyota Motor Corporation. Operates 45 dealerships and service centers across the Chubu region, employing over 3,000 technicians and staff. The company is at the forefront of hybrid and electric vehicle servicing and has been expanding its international technician recruitment program since 2020.",
    placement: { city: "Nagoya", state: "Aichi", country: "Japan" },
    termsAndConditions: {
      durationOfContract: "36 bulan (perpanjangan berdasarkan evaluasi)",
      annualLeave: "18 hari kerja/tahun",
      probationPeriod: "3 bulan",
      workingDays: "Senin–Sabtu (Sabtu half-day, rotasi libur)",
      workingHours: "40 jam/minggu",
    },
    documentRequirements: [
      "Paspor", "CV Candidate", "Ijazah", "Transkrip Nilai",
      "Surat Pengalaman Kerja", "Akta Kelahiran", "Kartu Tanda Penduduk",
      "Kartu Keluarga", "Surat Izin Orang Tua (jika < 21 tahun)",
    ],
    requiredSubcourses: [
      "Nihongo N5", "Nihongo N4",
      "Sistem Mesin dan Komponen Kendaraan", "Diagnostik Kendaraan Modern",
      "Teknologi Hybrid dan Kendaraan Listrik", "Perawatan Berkala Kendaraan",
      "Keselamatan Kerja di Bengkel", "Membaca Manual dan Instruksi Teknis",
      "Alat Diagnostik dan Pengukuran", "Standar Keselamatan Kendaraan Jepang",
    ],
  },
  {
    id: "job_014",
    title: "Juru Las & Fabrikasi Logam (溶接技能者)",
    company: "Hitachi Zosen Corporation (日立造船株式会社)",
    offTaker: "APJATI",
    country: "Japan",
    countryFlag: "🇯🇵",
    sector: "Manufacturing",
    salaryMin: 15000000,
    salaryMax: 22000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-11T00:00:00Z",
    deadline: "2025-06-30T00:00:00Z",
    positions: 20,
    description:
      "Perform precision welding and metal fabrication for industrial manufacturing, shipbuilding, and infrastructure projects in Osaka's industrial district. Execute MIG, TIG, and arc welding techniques on various metals, read and interpret engineering blueprints, and ensure all welds meet Japanese Industrial Standards (JIS) quality specifications.",
    qualifications: [
      "Male / Female",
      "Age 21–40 years old",
      "Minimum SMK or vocational training in Welding, Metalworking, or Mechanical Engineering",
      "Minimum 2 years of professional welding experience",
      "Welding certification (AWS, JIS, or equivalent) preferred",
      "Minimum Japanese language proficiency level JLPT N4",
      "Physically fit and comfortable working in industrial environments",
    ],
    benefits: [
      "Sponsored Japanese language training up to JLPT N3",
      "JIS welding certification training and exam sponsorship",
      "Accommodation provided throughout contract period",
      "Meals provided during working shifts",
      "Overtime pay at 125%–150% standard rate",
      "Pathway to Specified Skilled Worker visa renewal",
      "Annual flight allowance to home country",
    ],
    isFunded: false,
    skillRequirements: [
      { skillName: "Basic Decision-Making", requiredLevel: 65, userLevel: 30 },
      { skillName: "Productivity and Management Skills", requiredLevel: 70, userLevel: 55 },
      { skillName: "Basic Thinking Skills", requiredLevel: 60, userLevel: 45 },
    ],
    employerInfo:
      "A major Japanese industrial conglomerate headquartered in Osaka, specializing in environmental systems, industrial plants, shipbuilding, and steel fabrication. Founded in 1881, Hitachi Zosen employs over 11,000 workers globally and is a key contractor for Japan's infrastructure, energy, and maritime sectors.",
    placement: { city: "Osaka", state: "Osaka", country: "Japan" },
    termsAndConditions: {
      durationOfContract: "36 bulan (perpanjangan berdasarkan evaluasi)",
      annualLeave: "18 hari kerja/tahun",
      probationPeriod: "3 bulan",
      workingDays: "Senin–Sabtu (Sabtu half-day, rotasi)",
      workingHours: "40 jam/minggu",
    },
    documentRequirements: [
      "Paspor", "CV Candidate", "Ijazah", "Transkrip Nilai",
      "Surat Pengalaman Kerja", "Akta Kelahiran", "Kartu Tanda Penduduk",
      "Kartu Keluarga", "Surat Izin Orang Tua (jika < 21 tahun)",
    ],
    requiredSubcourses: [
      "Nihongo N5", "Nihongo N4",
      "Teknik Las MIG, TIG, dan Arc", "Jenis Logam dan Karakteristiknya",
      "Membaca Gambar Teknis dan Blueprint", "Keselamatan Kerja di Lingkungan Industri",
      "Standar Kualitas Las Jepang (JIS)", "Inspeksi dan Kontrol Kualitas",
      "Alat Ukur dan Fabrikasi", "Perawatan Peralatan Las",
    ],
  },
  {
    id: "job_015",
    title: "Perawat Rumah Sakit (간호사)",
    company: "Samsung Medical Center (삼성서울병원)",
    offTaker: "APJATI",
    country: "South Korea",
    countryFlag: "🇰🇷",
    sector: "Healthcare",
    salaryMin: 18000000,
    salaryMax: 26000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-04T00:00:00Z",
    deadline: "2025-06-30T00:00:00Z",
    positions: 15,
    description:
      "Provide professional nursing care in one of South Korea's top-tier university hospitals. Conduct patient assessments, assist in surgical procedures, manage post-operative care, and ensure accurate electronic medical record documentation. Work within Korea's technologically advanced healthcare system alongside a multidisciplinary medical team.",
    qualifications: [
      "Male / Female",
      "Age 22–34 years old",
      "Minimum Bachelor's Degree (S1) in Nursing",
      "Active STR (Surat Tanda Registrasi Keperawatan)",
      "Minimum 1 year of clinical experience",
      "Minimum Korean language proficiency level TOPIK 3",
      "Willingness to obtain Korean nursing license (간호사 면허)",
    ],
    benefits: [
      "Sponsored Korean language training up to TOPIK 4",
      "Sponsored preparation for Korean nursing license exam",
      "Accommodation provided for the first 12 months",
      "Pathway to E-7 Professional Work Visa renewal",
      "Annual flight allowance to home country",
      "Bonus for passing Korean nursing license exam",
    ],
    isFunded: true,
    funderName: "Korean Ministry of Health and Welfare — Foreign Nurse Recruitment Programme",
    mpChannel: "zenius",
    skillRequirements: [
      { skillName: "Basic Thinking Skills", requiredLevel: 70, userLevel: 45 },
      { skillName: "Understanding and Be Effective with Others", requiredLevel: 80, userLevel: 60 },
      { skillName: "Communication in Japanese/Korean/English", requiredLevel: 70, userLevel: 20 },
    ],
    employerInfo:
      "One of South Korea's most prestigious hospitals, affiliated with Sungkyunkwan University School of Medicine. Located in Gangnam-gu, Seoul, the center operates 1,989 beds across 44 specialized departments. Ranked consistently among Asia's top 10 hospitals, Samsung Medical Center is a leader in oncology, organ transplantation, and robotic surgery.",
    placement: { city: "Seoul", state: "Seoul", country: "South Korea" },
    termsAndConditions: {
      durationOfContract: "36 bulan (perpanjangan berdasarkan evaluasi dan lisensi)",
      annualLeave: "15 hari kerja/tahun",
      probationPeriod: "6 bulan",
      workingDays: "Senin–Minggu (shift system)",
      workingHours: "40 jam/minggu",
    },
    documentRequirements: [
      "Paspor", "CV Candidate", "Resume", "Ijazah", "Transkrip Nilai",
      "Surat Tanda Registrasi Keperawatan", "Surat Pengalaman Kerja",
      "BPJS", "Akta Kelahiran", "Kartu Tanda Penduduk", "Kartu Keluarga",
    ],
    requiredSubcourses: [
      "Hangugeo Beginner 1", "Hangugeo Beginner 2", "Hangugeo Intermediate",
      "Komunikasi dengan Pasien Korea", "Dasar Istilah Medis Korea",
      "Dokumentasi Medis Elektronik", "Sistem Kesehatan dan Asuransi Korea",
      "Farmakologi Dasar", "Etika Keperawatan di Korea",
      "Persiapan Ujian Lisensi Keperawatan Korea",
    ],
  },
  {
    id: "job_016",
    title: "Teknisi Galangan Kapal (조선기술자)",
    company: "Hanwha Ocean Co., Ltd. (한화오션)",
    offTaker: "Mitra Kerja Nusantara",
    country: "South Korea",
    countryFlag: "🇰🇷",
    sector: "Manufacturing",
    salaryMin: 16000000,
    salaryMax: 24000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-12T00:00:00Z",
    deadline: "2025-06-30T00:00:00Z",
    positions: 30,
    description:
      "Perform precision assembly, welding, and outfitting work at one of the world's largest shipbuilding complexes. Contribute to the construction of LNG carriers, container ships, and offshore platforms using advanced fabrication techniques. Work alongside Korean master technicians in a high-output industrial environment with strict quality and safety standards.",
    qualifications: [
      "Male / Female",
      "Age 21–40 years old",
      "Minimum SMK or vocational training in Welding, Shipbuilding, or Mechanical Engineering",
      "Minimum 2 years of welding or heavy fabrication experience",
      "Welding certification (AWS, KS, or equivalent) preferred",
      "Minimum Korean language proficiency level TOPIK 2",
      "Physically fit and comfortable working at heights and in confined spaces",
    ],
    benefits: [
      "Sponsored Korean language training up to TOPIK 3",
      "KS welding certification training and exam sponsorship",
      "Dormitory accommodation provided throughout contract",
      "Meals provided during working shifts",
      "Overtime pay at 150% standard rate",
      "Pathway to E-9 Visa renewal or E-7 upgrade",
      "Annual flight allowance to home country",
    ],
    isFunded: false,
    mpChannel: "telkomsel",
    skillRequirements: [
      { skillName: "Basic Decision-Making", requiredLevel: 65, userLevel: 30 },
      { skillName: "Productivity and Management Skills", requiredLevel: 70, userLevel: 55 },
      { skillName: "Basic Thinking Skills", requiredLevel: 60, userLevel: 45 },
    ],
    employerInfo:
      "Formerly known as Daewoo Shipbuilding & Marine Engineering (DSME), Hanwha Ocean is one of the world's top three shipbuilders, headquartered in Geoje Island. The company specializes in LNG carriers, ultra-large container ships, submarines, and offshore platforms. With over 20,000 employees and a 4.3km-long dry dock, Hanwha Ocean recruits thousands of international skilled workers annually.",
    placement: { city: "Geoje", state: "South Gyeongsang", country: "South Korea" },
    termsAndConditions: {
      durationOfContract: "36 bulan (perpanjangan berdasarkan evaluasi)",
      annualLeave: "15 hari kerja/tahun",
      probationPeriod: "3 bulan",
      workingDays: "Senin–Sabtu (Sabtu half-day, rotasi)",
      workingHours: "44 jam/minggu",
    },
    documentRequirements: [
      "Paspor", "CV Candidate", "Ijazah", "Transkrip Nilai",
      "Surat Pengalaman Kerja", "Akta Kelahiran", "Kartu Tanda Penduduk",
      "Kartu Keluarga", "Surat Izin Orang Tua (jika < 21 tahun)",
    ],
    requiredSubcourses: [
      "Hangugeo Beginner 1", "Hangugeo Beginner 2",
      "Teknik Las untuk Konstruksi Kapal", "Jenis Logam dan Material Maritim",
      "Membaca Blueprint Galangan Kapal", "Keselamatan Kerja di Lingkungan Maritim",
      "Standar Kualitas Pengelasan Korea (KS)", "Perakitan dan Outfitting Kapal",
      "Alat Berat dan Crane Operation Dasar", "Prosedur Darurat di Galangan",
    ],
  },
  {
    id: "job_017",
    title: "Perawat Geriatri (老人護理員)",
    company: "Haven of Hope Christian Service (基督教靈實協會)",
    offTaker: "BINAWAN",
    country: "Hong Kong SAR",
    countryFlag: "🇭🇰",
    sector: "Care Worker",
    salaryMin: 12000000,
    salaryMax: 18000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-06T00:00:00Z",
    deadline: "2025-06-30T00:00:00Z",
    positions: 25,
    description:
      "Provide professional elderly care services in Hong Kong's expanding network of residential care homes and community health centers. Assist elderly residents with daily living activities, coordinate with physicians for chronic disease management, and implement individualized wellness programs. Support Hong Kong's aging population through compassionate, culturally sensitive care.",
    qualifications: [
      "Male / Female",
      "Age 22–35 years old",
      "Minimum Diploma III (D3) in Nursing or Elderly Care",
      "Minimum 1 year of elderly care or clinical experience",
      "Minimum IELTS score of 5.5 or equivalent English proficiency",
      "Basic Cantonese language willingness to learn",
      "Patient, respectful, and culturally sensitive",
    ],
    benefits: [
      "Sponsored Cantonese language training",
      "Accommodation provided throughout contract period",
      "Pathway to Hong Kong Employment Visa renewal",
      "Medical and dental insurance",
      "Annual flight allowance to home country",
      "Professional development in geriatric care",
    ],
    isFunded: true,
    funderName: "Hong Kong Social Welfare Department — Supplementary Labour Scheme (SLS)",
    skillRequirements: [
      { skillName: "Understanding and Be Effective with Others", requiredLevel: 85, userLevel: 60 },
      { skillName: "Communication in Japanese/Korean/English", requiredLevel: 65, userLevel: 20 },
      { skillName: "Basic Thinking Skills", requiredLevel: 60, userLevel: 45 },
    ],
    employerInfo:
      "One of Hong Kong's largest non-profit elderly care and healthcare providers, operating since 1953. Haven of Hope manages 12 residential care homes, 5 community health centers, and 3 rehabilitation facilities across the New Territories and Kowloon. The organization serves over 4,000 elderly residents and is a leading participant in Hong Kong's Supplementary Labour Scheme.",
    placement: { city: "Hong Kong", state: "New Territories", country: "Hong Kong SAR" },
    termsAndConditions: {
      durationOfContract: "24 bulan (perpanjangan berdasarkan evaluasi)",
      annualLeave: "14 hari kerja/tahun",
      probationPeriod: "3 bulan",
      workingDays: "Senin–Sabtu (rotasi shift, 1 hari libur/minggu)",
      workingHours: "44 jam/minggu",
    },
    documentRequirements: [
      "Paspor", "CV Candidate", "Resume", "Ijazah", "Transkrip Nilai",
      "Surat Pengalaman Kerja", "BPJS", "Akta Kelahiran",
      "Kartu Tanda Penduduk", "Kartu Keluarga",
    ],
    requiredSubcourses: [
      "English Beginner", "English Intermediate", "Cantonese Dasar",
      "Komunikasi dengan Pasien Lansia", "Perawatan Lansia dan Aktivitas Harian",
      "Manajemen Penyakit Kronis", "Nutrisi dan Diet untuk Lansia",
      "Dokumentasi Perawatan", "Pertolongan Pertama dan Penanganan Darurat",
      "Budaya dan Etiket di Hong Kong",
    ],
  },
  {
    id: "job_018",
    title: "Koki & Profesional F&B (廚師及餐飲專業人員)",
    company: "Maxim's Caterers Limited (美心食品有限公司)",
    offTaker: "APJATI",
    country: "Hong Kong SAR",
    countryFlag: "🇭🇰",
    sector: "Hospitality",
    salaryMin: 14000000,
    salaryMax: 20000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-08T00:00:00Z",
    deadline: "2025-06-30T00:00:00Z",
    positions: 20,
    description:
      "Work as a skilled culinary professional in Hong Kong's world-class dining scene. Prepare and present dishes in a high-volume, internationally acclaimed restaurant environment. Collaborate with executive chefs on menu development, maintain exceptional food quality standards, and contribute to one of Asia's most vibrant food cultures.",
    qualifications: [
      "Male / Female",
      "Age 21–35 years old",
      "Minimum SMK or Diploma in Culinary Arts, Hospitality, or Food & Beverage",
      "Minimum 2 years of professional kitchen experience",
      "Competent in at least one cuisine specialty (Asian, Western, or pastry)",
      "Minimum IELTS score of 5.0 or equivalent English proficiency",
      "Able to work in fast-paced, high-pressure kitchen environments",
    ],
    benefits: [
      "Work alongside Michelin-starred and award-winning chefs",
      "Accommodation assistance for the first 3 months",
      "Meals provided during working shifts",
      "Pathway to Hong Kong Employment Visa renewal",
      "Medical insurance",
      "Career progression to Sous Chef and Executive Chef roles",
    ],
    isFunded: false,
    mpChannel: "zenius",
    skillRequirements: [
      { skillName: "Communication in Japanese/Korean/English", requiredLevel: 65, userLevel: 20 },
      { skillName: "Productivity and Management Skills", requiredLevel: 70, userLevel: 55 },
      { skillName: "Basic Thinking Skills", requiredLevel: 60, userLevel: 45 },
    ],
    employerInfo:
      "Hong Kong's largest food and beverage conglomerate, operating over 1,600 outlets across Hong Kong, China, and Southeast Asia. Maxim's portfolio spans fine dining restaurants, casual eateries, bakeries, and institutional catering. The company holds franchise rights for Starbucks and Genki Sushi in Hong Kong and employs over 35,000 staff.",
    placement: { city: "Hong Kong", state: "Hong Kong Island", country: "Hong Kong SAR" },
    termsAndConditions: {
      durationOfContract: "24 bulan (perpanjangan berdasarkan evaluasi)",
      annualLeave: "14 hari kerja/tahun",
      probationPeriod: "3 bulan",
      workingDays: "Senin–Minggu (shift system, 1 hari libur/minggu)",
      workingHours: "48 jam/minggu",
    },
    documentRequirements: [
      "Paspor", "CV Candidate", "Cover Letter", "Ijazah", "Transkrip Nilai",
      "Surat Pengalaman Kerja", "Akta Kelahiran", "Kartu Tanda Penduduk",
      "Kartu Keluarga", "Surat Izin Orang Tua (jika < 21 tahun)",
    ],
    requiredSubcourses: [
      "English Beginner", "English Intermediate",
      "Teknik Memasak Internasional", "Kebersihan dan Keamanan Pangan",
      "Manajemen Dapur Profesional", "Presentasi dan Plating",
      "Pengelolaan Inventaris dan Bahan Baku", "Menu Development dan Food Costing",
      "Komunikasi di Lingkungan Dapur",
    ],
  },
  {
    id: "job_019",
    title: "Perawat & Tenaga Medis (ممرض/ة)",
    company: "Cleveland Clinic Abu Dhabi",
    offTaker: "BINAWAN",
    country: "United Arab Emirates",
    countryFlag: "🇦🇪",
    sector: "Healthcare",
    salaryMin: 24000000,
    salaryMax: 34000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-05T00:00:00Z",
    deadline: "2025-07-31T00:00:00Z",
    positions: 15,
    description:
      "Deliver high-quality nursing care in a state-of-the-art hospital facility in Abu Dhabi. Manage diverse patient populations from over 200 nationalities, perform clinical assessments, administer treatments, and maintain documentation in compliance with UAE Department of Health (DOH) standards. Work within a rapidly growing healthcare ecosystem that blends cutting-edge technology with multicultural patient care.",
    qualifications: [
      "Male / Female",
      "Age 23–35 years old",
      "Minimum Bachelor's Degree (S1) in Nursing",
      "Active STR (Surat Tanda Registrasi Keperawatan)",
      "Minimum 2 years of clinical experience",
      "Minimum IELTS score of 6.5 (or OET Grade B)",
      "Willingness to obtain DOH or DHA nursing license",
    ],
    benefits: [
      "Tax-free salary",
      "Furnished accommodation provided",
      "Annual flight ticket to home country",
      "Medical and dental insurance for employee and dependents",
      "Sponsored DOH/DHA licensing process",
      "30 days paid annual leave",
      "End-of-service gratuity as per UAE Labour Law",
    ],
    isFunded: true,
    funderName: "Abu Dhabi Health Services Company (SEHA) — International Recruitment Programme",
    mpChannel: "telkomsel",
    skillRequirements: [
      { skillName: "Basic Thinking Skills", requiredLevel: 75, userLevel: 45 },
      { skillName: "Understanding and Be Effective with Others", requiredLevel: 80, userLevel: 60 },
      { skillName: "Communication in Japanese/Korean/English", requiredLevel: 75, userLevel: 20 },
    ],
    employerInfo:
      "A world-class multispecialty hospital on Al Maryah Island, Abu Dhabi, and the first international extension of the renowned Cleveland Clinic (USA). The 364-bed facility houses 13 specialized institutes and is staffed by over 4,000 professionals from 80+ nationalities. The hospital is JCI-accredited and consistently ranked among the best in the Middle East.",
    placement: { city: "Abu Dhabi", state: "Abu Dhabi", country: "United Arab Emirates" },
    termsAndConditions: {
      durationOfContract: "24 bulan (perpanjangan berdasarkan evaluasi)",
      annualLeave: "30 hari kalender/tahun",
      probationPeriod: "6 bulan",
      workingDays: "Senin–Minggu (shift system)",
      workingHours: "48 jam/minggu",
    },
    documentRequirements: [
      "Paspor", "CV Candidate", "Resume", "Ijazah", "Transkrip Nilai",
      "Surat Tanda Registrasi Keperawatan", "Surat Pengalaman Kerja",
      "BPJS", "Akta Kelahiran", "Kartu Tanda Penduduk", "Kartu Keluarga",
    ],
    requiredSubcourses: [
      "English Beginner", "English Intermediate", "English Advanced",
      "Komunikasi dengan Pasien Multikultural", "Istilah Medis dalam Bahasa Inggris",
      "Dokumentasi Klinis Standar Internasional", "Sistem Kesehatan UAE dan Regulasi DOH",
      "Farmakologi Dasar", "Etika Keperawatan Internasional",
      "Arabic Dasar untuk Tenaga Medis",
    ],
  },
  {
    id: "job_020",
    title: "Teknisi Mekanikal & HVAC (فني ميكانيكي)",
    company: "Emaar Properties PJSC",
    offTaker: "Mitra Kerja Nusantara",
    country: "United Arab Emirates",
    countryFlag: "🇦🇪",
    sector: "Construction",
    salaryMin: 17000000,
    salaryMax: 25000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-10T00:00:00Z",
    deadline: "2025-07-31T00:00:00Z",
    positions: 30,
    description:
      "Install, maintain, and troubleshoot mechanical systems including HVAC, plumbing, fire protection, and building management systems across large-scale commercial and hospitality developments in Dubai. Work on iconic infrastructure projects in one of the world's fastest-growing cities, ensuring systems meet international standards and operate at peak efficiency in extreme desert climate conditions.",
    qualifications: [
      "Male / Female",
      "Age 22–40 years old",
      "Minimum SMK or Diploma in Mechanical Engineering, HVAC, or Building Services",
      "Minimum 2 years of experience in HVAC installation, maintenance, or building mechanical systems",
      "Familiarity with VRF/VRV systems, chillers, and BMS preferred",
      "Minimum English proficiency for technical communication",
      "Valid technical certifications (City & Guilds, BTEC, or equivalent) preferred",
    ],
    benefits: [
      "Tax-free salary",
      "Shared accommodation provided",
      "Annual flight ticket to home country",
      "Medical insurance",
      "Overtime pay at 125% standard rate",
      "End-of-service gratuity as per UAE Labour Law",
      "Opportunity to obtain UAE Estidama or LEED certification",
    ],
    isFunded: false,
    skillRequirements: [
      { skillName: "Basic Decision-Making", requiredLevel: 65, userLevel: 30 },
      { skillName: "Productivity and Management Skills", requiredLevel: 70, userLevel: 55 },
      { skillName: "Basic Thinking Skills", requiredLevel: 65, userLevel: 45 },
    ],
    employerInfo:
      "The UAE's largest real estate developer and the company behind Burj Khalifa, Dubai Mall, and Dubai Marina. Emaar Properties manages a portfolio spanning residential, commercial, hospitality, and leisure assets across 6 countries. With over 10,000 employees, Emaar recruits thousands of international technicians and engineers annually for ongoing mega-developments.",
    placement: { city: "Dubai", state: "Dubai", country: "United Arab Emirates" },
    termsAndConditions: {
      durationOfContract: "24 bulan (perpanjangan berdasarkan evaluasi)",
      annualLeave: "30 hari kalender/tahun",
      probationPeriod: "6 bulan",
      workingDays: "Senin–Sabtu",
      workingHours: "48 jam/minggu (reduced hours during Ramadan)",
    },
    documentRequirements: [
      "Paspor", "CV Candidate", "Ijazah", "Transkrip Nilai",
      "Surat Pengalaman Kerja", "Akta Kelahiran", "Kartu Tanda Penduduk",
      "Kartu Keluarga", "Surat Izin Orang Tua (jika < 21 tahun)",
    ],
    requiredSubcourses: [
      "English Beginner", "English Intermediate",
      "Sistem HVAC dan Pendinginan", "Instalasi Plumbing dan Pipa",
      "Membaca Gambar Teknis MEP", "Keselamatan Kerja di Konstruksi",
      "Sistem Proteksi Kebakaran", "Building Management System (BMS) Dasar",
      "Perawatan Preventif Peralatan Mekanikal", "Standar Bangunan UAE dan Regulasi DEWA",
    ],
  },
  {
    id: "job_021",
    title: "Perawat RS Swasta (Registered Nurse)",
    company: "Parkway Pantai Limited (Mount Elizabeth Hospital)",
    offTaker: "APJATI",
    country: "Singapore",
    countryFlag: "🇸🇬",
    sector: "Healthcare",
    salaryMin: 22000000,
    salaryMax: 30000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-03T00:00:00Z",
    deadline: "2025-06-30T00:00:00Z",
    positions: 12,
    description:
      "Deliver patient-centered nursing care in one of Singapore's premier private hospital groups. Manage patient assessments, medication administration, wound care, and post-surgical monitoring across medical, surgical, and specialist wards. Work within Singapore's world-renowned healthcare system, serving a diverse international patient base in a technologically advanced clinical environment.",
    qualifications: [
      "Male / Female",
      "Age 22–35 years old",
      "Minimum Bachelor's Degree (S1) in Nursing",
      "Active STR (Surat Tanda Registrasi Keperawatan)",
      "Minimum 2 years of clinical experience",
      "Minimum IELTS score of 6.5 (or equivalent)",
      "Willingness to obtain Singapore Nursing Board (SNB) registration",
    ],
    benefits: [
      "Sponsored SNB registration and adaptation programme",
      "Subsidized accommodation in hospital staff housing",
      "Pathway to Singapore Permanent Residency (PR)",
      "Medical and dental insurance",
      "Annual flight allowance to home country",
      "Paid continuing professional development",
      "Performance bonus",
    ],
    isFunded: true,
    funderName: "Singapore Ministry of Health (MOH) — Healthcare Manpower Plan",
    mpChannel: "zenius",
    skillRequirements: [
      { skillName: "Basic Thinking Skills", requiredLevel: 70, userLevel: 45 },
      { skillName: "Understanding and Be Effective with Others", requiredLevel: 80, userLevel: 60 },
      { skillName: "Communication in Japanese/Korean/English", requiredLevel: 75, userLevel: 20 },
    ],
    employerInfo:
      "Part of IHH Healthcare — the world's second-largest private healthcare group. Mount Elizabeth Hospital in Orchard Road is Singapore's flagship premium hospital, operating 345 beds with over 30 specialist centers. The hospital serves patients from across Southeast Asia and the Middle East, and is consistently ranked among Asia-Pacific's top private hospitals.",
    placement: { city: "Singapore", state: "Singapore", country: "Singapore" },
    termsAndConditions: {
      durationOfContract: "24 bulan (perpanjangan berdasarkan evaluasi)",
      annualLeave: "14 hari kerja/tahun (meningkat sesuai masa kerja)",
      probationPeriod: "6 bulan",
      workingDays: "Senin–Minggu (shift system)",
      workingHours: "44 jam/minggu",
    },
    documentRequirements: [
      "Paspor", "CV Candidate", "Resume", "Cover Letter", "Ijazah", "Transkrip Nilai",
      "Surat Tanda Registrasi Keperawatan", "Surat Pengalaman Kerja",
      "BPJS", "Akta Kelahiran", "Kartu Tanda Penduduk", "Kartu Keluarga",
    ],
    requiredSubcourses: [
      "English Beginner", "English Intermediate", "English Advanced",
      "Komunikasi dengan Pasien Multikultural", "Istilah Medis dalam Bahasa Inggris",
      "Dokumentasi Klinis Standar Internasional", "Farmakologi Dasar",
      "Etika Keperawatan Internasional", "Penulisan Laporan Medis",
      "Sistem Kesehatan Singapura dan Regulasi MOH",
    ],
  },
  {
    id: "job_022",
    title: "Teknisi Semikonduktor (Semiconductor Technician)",
    company: "GlobalFoundries Singapore Pte. Ltd.",
    offTaker: "Mitra Kerja Nusantara",
    country: "Singapore",
    countryFlag: "🇸🇬",
    sector: "Manufacturing",
    salaryMin: 18000000,
    salaryMax: 26000000,
    salaryCurrency: "IDR",
    postedAt: "2025-03-13T00:00:00Z",
    deadline: "2025-06-30T00:00:00Z",
    positions: 20,
    description:
      "Operate, monitor, and maintain advanced semiconductor fabrication equipment in Singapore's leading chip manufacturing facility. Perform wafer processing, conduct in-process quality inspections, troubleshoot equipment faults, and ensure production output meets stringent yield and quality targets. Work in a cleanroom environment at the cutting edge of global semiconductor manufacturing.",
    qualifications: [
      "Male / Female",
      "Age 21–35 years old",
      "Minimum Diploma III (D3) in Electrical Engineering, Electronics, Mechatronics, or Chemical Engineering",
      "Minimum 1 year of experience in semiconductor, electronics manufacturing, or precision engineering",
      "Comfortable working in cleanroom environments (gowning, ESD protocols)",
      "Minimum English proficiency for technical communication",
      "Willing to work rotating 12-hour shifts",
    ],
    benefits: [
      "Sponsored technical training on advanced fab equipment",
      "Subsidized accommodation",
      "Pathway to Singapore Employment Pass or S Pass renewal",
      "Medical and dental insurance",
      "Shift allowances and overtime pay",
      "Annual flight allowance to home country",
      "Career progression to Senior Technician and Process Engineer roles",
    ],
    isFunded: true,
    funderName: "Singapore Economic Development Board (EDB) — Precision Engineering Workforce Initiative",
    mpChannel: "telkomsel",
    skillRequirements: [
      { skillName: "Basic Thinking Skills", requiredLevel: 70, userLevel: 45 },
      { skillName: "Basic Decision-Making", requiredLevel: 65, userLevel: 30 },
      { skillName: "Productivity and Management Skills", requiredLevel: 70, userLevel: 55 },
    ],
    employerInfo:
      "One of the world's largest semiconductor foundries, with its Singapore campus in Woodlands housing two advanced wafer fabrication plants (Fab 7 and Fab 3E). The Singapore operations employ over 4,000 workers producing chips for automotive, IoT, 5G, and data center applications. GlobalFoundries Singapore is a key pillar of the country's semiconductor ecosystem.",
    placement: { city: "Singapore", state: "Singapore", country: "Singapore" },
    termsAndConditions: {
      durationOfContract: "24 bulan (perpanjangan berdasarkan evaluasi)",
      annualLeave: "14 hari kerja/tahun (meningkat sesuai masa kerja)",
      probationPeriod: "3 bulan",
      workingDays: "4 hari kerja / 4 hari libur (compressed shift rotation)",
      workingHours: "44 jam/minggu (12-hour rotating shifts)",
    },
    documentRequirements: [
      "Paspor", "CV Candidate", "Ijazah", "Transkrip Nilai",
      "Surat Pengalaman Kerja", "Akta Kelahiran", "Kartu Tanda Penduduk",
      "Kartu Keluarga", "Surat Izin Orang Tua (jika < 21 tahun)",
    ],
    requiredSubcourses: [
      "English Beginner", "English Intermediate",
      "Dasar Proses Fabrikasi Semikonduktor", "Pengoperasian Peralatan Cleanroom",
      "Kontrol Kualitas dan Yield Management", "Keselamatan Kerja di Lingkungan Cleanroom",
      "Dasar Elektronika dan Sirkuit", "Troubleshooting Peralatan Fabrikasi",
      "Membaca Spesifikasi Teknis dan SOP", "Standar ESD dan Kontaminasi",
    ],
  },
];

export const MARKETING_PARTNERS: MarketingPartner[] = [
  {
    id: "mp-zenius",
    name: "Zenius",
    slug: "zenius",
    tagline: "Belajar cerdas, karir global. Zenius × #KaburPortal.",
    color: "#E4002B",
    referralCount: 5420,
    activeJobCount: 38,
  },
  {
    id: "mp-telkomsel",
    name: "Telkomsel",
    slug: "telkomsel",
    tagline: "Koneksi terbaik untuk masa depan PMI Indonesia.",
    color: "#E4002B",
    referralCount: 4980,
    activeJobCount: 52,
  },
  {
    id: "ot-vokati",
    name: "Vokati",
    slug: "vokati",
    tagline: "Penempatan kerja luar negeri terpercaya — verifikasi dan pendampingan profesional.",
    color: "#1E40AF",
    referralCount: 0,
    activeJobCount: 142,
    ctaHref: "/home",
    ctaLabel: "→ Lihat lowongan",
  },
  {
    id: "ot-apjati",
    name: "APJATI",
    slug: "apjati",
    tagline: "Asosiasi Perusahaan Jasa Tenaga Kerja Indonesia — penempatan PMI resmi dan berizin.",
    color: "#B45309",
    referralCount: 0,
    activeJobCount: 98,
    ctaHref: "/home",
    ctaLabel: "→ Lihat lowongan",
  },
];
